cmd/yagpdb/templates/plugins/serverstats.html
Replaced: fa-user -> fa-user-plus ; "fa-trash" for "Online members" -> fa-user ; "fa-trash" for "Total members" -> fa-users
=> Serverstats: Better fitting FA-Icons

cmd/yagpdb/static/dist/css/yagpdb.css
Callouts would be a good design choice for info related stuff in future uses
=> CSS for Callouts

cmd/yagpdb/templates/plugins/logging.html
Hope this doesn't * up the css...
=> Prep. for Callouts

automod/assets/help-page.md
=> Help Docs (Grammar fixes)

cmd/yagpdb/static/dist/js/spongebob.js
You get a response and you get a response everybody gets a response! (7 new ones that are even worse then the others)
=> More reponses when loading on cp

cmd/yagpdb/static/dist/js/spongebob.js
=> More of these because why not

autorole/assets/settings.html
Updated autorole to show a disclaimer
=> Autorole update

stdcommands/throwthings.go
I like throwing things at other things
=> Throw update

cmd/yagpdb/posts/34-log-0.26.md
NOTE: This patch introduces a fix to the website/changelogs.
=> Update 34-log-0.26.md - Changelog Update

cmd/yagpdb/posts/35-log-0.27.md
NOTE: This patch introduces a fix to the website/changelogs.
=> i am also an uppercase I.... - Changelog Update

moderation/moderation.go
=> Grammar & Typos in Moderation

README.md
=> Grammar & Typo Fixes -- Fixing Jonas' Crap in README.md (THE MAIN ONE)

cmd/yagpdb/templates/plugins/soundboard.html
=> another spelling/grammar thing

reputation/plugin_bot.go
[x] "You can't give yourself ___" --> "You can't modify your own ___"
=> [Reputation Changes] Grammar Fixes

common/templates/context.go
https://github.com/jonas747/yagpdb/issues/225
=> fixed typo

web/validation.go, web/validation_test.go
Working on a feature request where I thought I'd need slices, but, as that no longer appears to be the case, submitting a pull request with no intent to use. It has tests so isn't all bad. 😄 
I fixed the other unit tests along the way as they were simple enough.
=> Web validation: Fix tests, add support for slices

stdcommands/general_commands.go, stdcommands/poll.go
Usage:
-poll "Which indent?" tabs spaces "carriage returns are for posers"
=> poll: New standard command for creating reaction polls

stdcommands/catfact/catfacts.go
looks like someone was just doing copy and paste xD
=> corrected html to discord formatting

automod/assets/automod.html
=> Grammar & Typo Fixed

docs/templates/ads.md
=> Updated $price/day

rolecommands/menu.go
Typos :)
Also, I have made "react on the original message" bold as many people don't read this part.
=> Fixed typos and made "original message" bold

cmd/yagpdb/templates/index.html
added link to my github + removed some unnecessary comments
=> improvements

cmd/yagpdb/templates/cp_nav.html
Fix the invite link that I added (actually goes to #faq now)
=> Update invite link *fix

stdcommands/poll/poll.go
This is one way to show username if nickname is not set in Discord. Currently this if clause is executed even if nick is not set,
=> updated poll.go to show username.

yagpdb_docker/Dockerfile
=> Add requirements back

automod/assets/automod.html
if not either the number or the word is wrong 💯
=> I think it was one month wasn't it

cmd/yagpdb/templates/cp_main.html
=> unified capitalization of YAGPDB long form :v

automod/assets/automod.html
Like previous html assets have, added target="_blank" to two of links here
=> added target="_blank"

cmd/yagpdb/static/css/custom.css
=> I am autistic, last fix i swear

stdcommands/advice/advice.go
a typo fix, just in case, before people start complaining : )
=> quick typo fix

rolecommands/menu.go
This was suggested by 🐾Roxien🐾He/Him🐾#0037, so I tried doing it. Not sure if it is right.
=> Added group name to default role-menu

autorole/assets/autorole.html
https://www.grammarly.com/blog/therefore-vs-therefor/
=> changed therfor to therefore

stdcommands/advice/advice.go
=> updated advice.go

stdcommands/advice/advice.go
=> oops forgot. http,url libraries

cmd/yagpdb/templates/index.html
This includes typos, updates for YAGPDB, and incorrect links.
=> Update Landing Page

commands/tmplexec.go
=> small typo fix

stdcommands/simpleembed/simpleembed.go
Added a switch for image in the simple embed command.
=> Simple Embed Image

cmd/yagpdb/static/vendor/codemirror/mode/python/index.html, stdcommands/listroles/listroles.go
=> Spelling fix

cmd/yagpdb/templates/index.html
as it's no longer *super fast* :P
=> updated reddit feed information

stdcommands/advice/advice.go
=> Grammar Fix

cmd/yagpdb/templates/index.html
Very minor changes: fixed a few grammar and spelling issues.
=> Grammar & Spelling Fixes

stdcommands/info/info.go
Capitalized proper nouns - yay grammar.
=> Proper Nouns - Grammar Fixes

README.md
More coming after you merge this and I find more of them xd.
=> Typo & Grammar Fixes

README.md, automod/README.md, automod/assets/automod.html, autorole/assets/autorole.html, aylien/aylien.go, cah/commands.go, cah/plugin_bot.go, discordlogger/README.md, notifications/README.md, premium/README.md, premium/assets/premium.html
More grammar, spelling, spaces, capitals, words, and stuff that were fixed.
=> Here's more fixes in one PR :)

automod/commands.go
=> Capitalization Consistancy

rolecommands/menu.go
Mostly capitalization, sometimes wording.
=> Made some cosmetic changes

common/templates/general.go
=> added function ToDuration

common/templates/context.go
part of function ToDuration in general.go
=> added toDuration

automod/automod.go, automod/automod_test.go
I added a third check to automod function PrepareMessageForWordCheck to leave the string as is and test the words in it as well. It continues to work for your test cases (slightly modified for third test case) as well as mine where I was trying to blacklist bot commands. It looks like you were intentionally looking at words only though so maybe there is a reason for that I'm not aware of.
Side note
If this ends up being my first successful pull request outside of school I might cry a little.
Great work on this bot. I really like it.
=> autoMod adjustment

CONTRIBUTING.md, README.md, SUGGESTION_TEMPLATE.md, cmd/yagpdb/templates/cp_logs.html, cmd/yagpdb/templates/cp_nav.html, cmd/yagpdb/templates/index.html
=> Updated all (hopefully) of the discord invites on the cp to the new faq channel

README.md, yagpdb_docker/Dockerfile, yagpdb_docker/docker-compose.override.yml, yagpdb_docker/docker-compose.proxied.yml, yagpdb_docker/docker-compose.proxy.yml, yagpdb_docker/docker-compose.yml
See individual commits for more explanation.
=> Docker: Refactor config, update, and fix a few issues

youtube/feed.go
=> Uploaded to uploaded typo

customcommands/bot.go
was "suggested" in #bugs channel, could be usable
=> suggestion for return if no CCs available

commands/plugin_bot.go
this is one way to fix it when people mistype help argument or even wrong argument and will not get 5/6 DMs every time
=> suggestion for help command

common/templates/context.go, common/templates/general.go
I am currently using this approach myself, maybe needs some changes
=> idea for round function

yagpdb_docker/docker-compose.yml
Things added/changed
- Added open ports by default (reverse proxy situations are defined in the other configurations)
- Add the ability to specify flags here ([ENTRYPOINT](https://docs.docker.com/engine/reference/#entrypoint) and [COMMAND](https://docs.docker.com/compose/compose-file/#command))
Related commit: https://github.com/casKd-dev/yagpdb/commit/8d950925d4ebad0314f24cf7d17e8c231a46d7f5
=> Adapt to latest image

cmd/yagpdb/main.go
at first was wondering why my twitter did not start, so remembered "feeds" : )
=> added twitter to help_feeds

timezonecompanion/plugin_bot.go
Suggestion, some further changes probably necessary.
=> updated setz -> added flags and slight changes

customcommands/assets/customcommands.html
=> quickfix > removed extra quote

stdcommands/stdcommands.go, stdcommands/xkcd/xkcd.go
I hope this fits to general bot's narrative... errors and embed part could be a bit wrong.
Currently runs fine, but I don't know all the nooks and crannies of the bot yet : )
gives random xkcd if no arguments given, optional arg is number and flag -l gives latest comic
=> suggestion: xkcd stdcommand

cmd/yagpdb/templates/cp_main.html
Bug originally found here:
https://discordapp.com/channels/166207328570441728/384011387132706816/586638439928299528
=> Fix missing ")" in template_helper_user

common/templates/context.go, common/templates/general.go
- I have added the mod function so we can easily calculate the modulus(Math.Mod)
=> Added mod command

customcommands/tmplextensions.go
- Added the dbDelById to delete any register using Id, since I had troubles deleting using keys, using Id would be a safe way to do it
=> Added dbDelById command

common/templates/general.go
=> updated seq > adjusted max length text

customcommands/tmplextensions.go
users have requested this and I am using something similar. Optionally counts rows regarding given user_id; or all table rows of current guild.
=> dbCount for templates

rolecommands/assets/rolecommands.html
Clarify the two single mode rolemenu specific options and their interactions.
=> Add a little info to mode specific rolemenu stuff

cmd/yagpdb/templates/index.html
Yag is three years old at this point.
=> Updated about

common/templates/context.go, common/templates/context_funcs.go
There is onlineCount to get all online users. This one will distinguish bots, having optionable bool argument which by default is true and counts all bots, but set to false, counts only online bots.
=> function countAllBots

common/templates/context.go
New Del function to remove an entry from SDict.
=> Added a new Del function for SDicts

common/templates/context.go, common/templates/context_funcs.go
Added a template to allow changing of channel topic. Have reused the same counters as used in tmplEditChannelName but probably might want to increase count for edit per channel per cc or use a different per channel tracker for topic change depending on review.
=> Satty9361 channel topic template

common/templates/context.go, common/templates/general.go
For some reason users want this, but yeah, it completes the basic math palette, so why not : )
=> subtraction function

automod/effects.go, moderation/commands.go, moderation/punishments.go
Made some changes to enable setting the number of days of messages to delete while executing the ban command.
=> Specifying Number of days of message to delete while executing ban command

moderation/commands.go
Based on discussion in [#dev-discussion](https://discordapp.com/channels/166207328570441728/578976869521555488)
=> Some Consistency fixes

customcommands/tmplextensions.go
Made some changes to the dbCount function which presently could only return total count per "UserID" and extended to also return total count per "Key" depending on optional argument datatype.
=> dbCount Addon to return total count per key

customcommands/tmplextensions.go
Referenced from Pull Request #504  
Added a function to implement append to slice ( restricted by maximum resulting slice length) using reflect.Append as per the latest feedback. I hope I have covered all corner cases while using reflect.Append.
=> append to slice template

moderation/commands.go
Ability to optionally ignore pinned messages while executing clean command with a new "-pin" flag.
Seems to work fine for me.
=> Clean: Optionally Ignore pinned messages

moderation/commands.go
Added a list violations moderation function. List all past violations of user ordering them by id , has an option to skip entries. Also included a summary mode and max age optional flags.
Permissions needed are manage messages permissions or roles allowed to give warnings.
=> Satty9361 list violations

stdcommands/mentionrole/mentionrole.go
Added a new flag to allow posting message in a different channel. 
Modified role searching to try to search by role ID if match using name is not found.
=> Mentionrole update to allow posting in specified channel and better role searching.

customcommands/assets/customcommands.html
I really think these things are necessary for CCs. 
Adding to CC Interval triggers - the time when they are next run, in server's locale. Did not use JavaScript there, can't see actual reason why. The layout formatting needs discussion due mobile screens.  (edit2: nothing to discuss actually, this is bootstrap .pull-right with frustrating-to-do vertical align and trigger text can actually be way longer than this Interval content is : )
Also because CCs response "size" is actually calculated using len function in customcommands.go returning bytes, my version has corrected character count (corrected, because Unicode emojis were not counted as one char) and byte count.
All in picture
=> updated customcommands.html

automod/commands.go, reputation/plugin_bot.go
Extending the paginated error patch to other similar commands ; referenced from PR #570 .
=> Satty9361 pagination patch rest

common/templates/context.go, common/templates/general.go, customcommands/tmplextensions.go
Implemented Slices as a separate datatype and reworked the Append function as a function of this new datatype. This should hopefully make it safe to have an append function without danger of mutating existing slices.
From my testing there is no problem with cembed, also the datatype is preserved after Append function or using "slice" function as well.
=> Slice as new Datatype and Append function update

automod/commands.go
A command to clear violations of an user similar to ClearWarnings with some filters and conditions. This should more or less finish the Violation related commands. I added a GuildScopeCooldown to prevent spamming of command because this command is probably a bit database heavy? Also i first fetched the rows then deleted them because "OrderBy" didnt seem to work with direct DeleteAll.
=> Clear Violations

common/templates/context.go
With slice as a new datatype, some additional functions to change value at an index of slice or appending two slices together will be helpful.
=> Satty9361 slice addon

customcommands/bot.go
Display the Custom Command group while running the cc command.
=> Display groups in cc command.

common/templates/general.go
It seems i forgot to change the return datatype in CreateSlice so a quick patch.
Thanks to @mrbentarikau  for bringing it to my notice.
=> Fix return Datatype in cslice

moderation/commands.go
Users have requested this quit a lot, it works well in conjunction with other flags, only thing probably is the name of the flag : )
=> addition to clean command: flag minAge

common/templates/general.go
An idea level pr to enable building SDicts from maps by extending the functionality of the sdict function. SDicts get converted to maps when stored in database or as execCC data so can be helpful in these cases.
Its an idea because technically this can also be achieved in CC code so more of a QoL thing.
=> IDEA: Increase functionality of sdict function

stdcommands/mentionrole/mentionrole.go
=> typofix for cmdFuncMentionRole return

automod/commands.go, common/templates/context_funcs.go, customcommands/bot.go
Just some prettying up and consistency fixed.
=> Format and Consistency Fixes

automod/effects.go, automod_legacy/bot.go, moderation/commands.go, moderation/plugin_bot.go, moderation/punishments.go, verification/verification_bot.go
Some changes to make .Channel and .Message available for punishment DMs( here these are the message/channel in which the Punishment is triggered either manually or by automod). This is especially useful when people want to send an extra message to the triggered channel or perform certain actions depending on content of original message and author of triggering message or send a custom DM depending on content of triggered message so on.
Lots of small changes, I hope i didnt forget anything.
=> Satty9361 punish data

common/templates/context.go, common/templates/general.go
We have square root, let's have some power :)
Also had to edit tmplMod "error of args length" return, because 0 is valid value for mod's return
=> template function: exponential power and modulo edit

customcommands/assets/customcommands.html
Forgot and for that else if  brach.
=> HTML Bugfix: missing and

moderation/assets/moderation.html, moderation/models.go, moderation/plugin_bot.go
Add ability to disallow reaction add while muting. (this prevents reaction spam). It can be handled by permissions but not the most efficiently in all situations.
Also bugfix : ChannelUpdate -> ChannelCreate
=> Satty9361 mute update

breaking_changes.md
=> Fix some typos

soundboard/bot.go, soundboard/player.go
Debug and Maintenance command for Soundboard, to reset queue and disconnect player.
This would be pretty helpful in general because currently there is no control over the bot while its in the voice channel or has many queued up files.
Hope the implementation is alright.
=> Satty9361 soundboard reset

cmd/yagpdb/templates/index.html
i know that quite a few people struggle to find this so i added a button on the top for /premium.
=> add quick access to premium on landing page

automod/effects.go
Add support for users to specify number of days of message to delete for ban effect through Automod V2.
=> Automod : Ban Delete Days

logs/plugin_bot.go
It's better to be in whois command than separate function for templates.
=> Idea: Member Status addition to Whois

timezonecompanion/plugin_bot.go
Dont know how this bug popped up but having this additional check is always good.
=> patch timezone responding to own messages bug

moderation/commands.go
Currently warning is one of the few commands which can span multiple messages and produce a great amount of spam. It should be paginated similar to many related commands such as : automod logs etc.
=> warning-pagination

moderation/commands.go
Fix bug where large warnings causes the command to crash due to embed limits.
=> Fix warnings pagination for very large warning reasons

automod/commands.go, moderation/commands.go, reputation/plugin_bot.go, timezonecompanion/plugin_bot.go
Some bug fixes and usability fixes when used with CCs
=> Satty9361 pagination fixes

common/templates/context.go, common/templates/context_funcs.go
We already have addRoleID and removeRoleID, so, why not also have addRoleName and removeRoleName?
=> New Role Functions

automod/automod_bot.go, automod/effects.go, automod/rulepart.go, common/scheduledevents2/builtinevents.go, moderation/commands.go
This is very much a requested feature. While give role effect can indeed remove roles (by giving roles for 1s), temporarily removing roles with amodV2 is not possible. Removing roles is a common punishment and as such should exist in amodV2 (eg : remove advertise role for 1hr for over posting).
=> Satty9361 Remove Role Effect amod2

common/templates/context.go, common/templates/general.go
For sdicts, we have .Del .Get and .Set
I thought it would be a good idea to have those for dicts aswell.
=> Help Methods

stdcommands/simpleembed/simpleembed.go
Simple additions of -content and -authorurl to the simple embed command which offers access to more options without increase in complexity.
=> simple additions to simpleembed command

automod_legacy/web.go, cmd/yagpdb/templates/cp_selectserver.html, customcommands/bot.go, rolecommands/web.go, verification/verification_web.go, web/handlers_general.go
An assortment of minor changes
=> Minor typo fixes, grammar fixes, and consistency fixes

common/templates/context_funcs.go
users have often requested for complexMessage support for DMs especially to send content + embed style messages. This extends that functionality to DMs.
=> Complex Message Support for sendDM

moderation/commands.go, stdcommands/customembed/customembed.go
Adds a new "-attachments" switch to the clean command, which if provided limits the clean operation to messages with attachments
=> Add flag to "clean" command to target only messages with attachments.

yagpdb_docker/app.example.env
Simply added a spot to enter Twitter API Keys to make it easier during initial setup of the file.
=> Added spot to enter Twitter API keys in app.env

customcommands/bot.go
This pull requests adds the following functionalities:
* Toggle syntax highlighting 
* Toggle file output
These are implemented using a switch, namely `-f` to toggle the file output, and `-h` to toggle highlighting. When given, they will turn on their respective effect. A demonstration with my selfhosted instance is attached as screenshot.
Thanks to @Pedro-Pessoa with cleaning up my messy beginner code and as usual, additional feedback is appreciated!
=> File and highlight switch for cc command

reminders/plugin_bot.go
As title says.
Works fine as far as I can tell on my selfhost.
=> reminders: add -a flag for delreminder to clear all

logs/assets/logs_control_panel.html, logs/web.go
Works fine as far as I can tell on selfhost.
=> logs: support deleting all message logs at once

moderation/commands.go
This allows users to only clear messages that do *not* match the given regex.
`-im` stands for **i**nvert regex **m**atch, ideally it've just been `-i` but that was taken already. Happy to bikeshed over naming.
Works fine on selfhost, as far as I can tell.
=> moderation: -im flag to invert regex match for clear cmd

customcommands/bot.go
This vastly improves error reporting in custom commands when possible.
**Changes**
* Instead of "ccid:line:column", use a more human readable representation
* Display the lines around where the error occurred in the error message
**Old**
**New**
=> cc: improve error reporting

logs/assets/logs_control_panel.html
Added missing space in "deletedmessages"
=> Corrected typos

moderation/commands.go
User suggestion on the server, makes it consistent with the other messages and removes the annoying pings.
Works fine on selfhost, as far as I can tell.
=> Embed report message

moderation/assets/moderation.html, moderation/punishments.go
See title.
Apologies for the formatting noise, that was just from gofmt. Happy to revert the formatting changes manually if you want.
=> moderation: add warning ID to context for warn punish DM

stdcommands/guildunavailable/guildunavilable.go
Fixed typo (Thanks to Ewgene#0006 for bringing this to my attention)
=> Typo fix guildunavilable.go

automod_legacy/assets/automod_legacy.html, cah/commands.go, commands/help.go, commands/yagcommmand.go, logs/assets/logs_view.html, logs/plugin_bot.go, moderation/modlog.go, reputation/plugin_bot.go, rolecommands/bot.go, rolecommands/menu.go, stdcommands/currentshard/currentshard.go, stdcommands/guildunavailable/guildunavilable.go, stdcommands/unbanserver/unbanserver.go, stdcommands/viewperms/viewperms.go, timezonecompanion/plugin_bot.go, web/middleware.go, web/util.go
Nothing much to say, see title.
No code logic is changed.
=> all: fix various user-facing typos around the code

youtube/web.go
Trim the YouTube URL part from the channel/name field when adding a YouTube feed. This is an exceptionally common mistake and relatively easy to fix as well.
The following will now be accepted and equivalent to `x`:
* `youtube.com/x`
* `www.youtube.com/c/x`
* `www.youtube.com/channel/x`
* `www.youtube.com/user/x`
* `https://www.youtube.com/user/x`
* ...and so on.
Works fine on selfhost, as far as I could tell.
=> youtube: trim youtube url part from yt channel/id

logs/plugin_bot.go
User suggestion, a channel flag for the log command.
Works fine on selfhost, as far as I can tell. Nothing much to explain on top of that 😄
=> Logs: Channel flag for log command

.github/workflows/action.yml
Found a small-ish mistake from #940. This pull request fixes that.
Sorry for the inconvenience :)
=> workflows: Remove unnecessary stuff, fix minor mistakes

stdcommands/currenttime/currenttime.go
Old user suggestion on the server, works fine on selfhost.
=> currenttime: use user timezone by default if set

customcommands/assets/customcommands.html
Relatively popular suggestion on the server suggested to move it to the left as it looks better, not much more to say :)
=> cc: move interval 'run now' btn to the left

cmd/yagpdb/templates/cp_nav.html
suppose I have 2 servers with the same name but different icons, this helps differentiate between them.
plus, I think it looks better than just a simple wrench
I have tested this on a selfhost and it seems to work fine 😃
=> show server icon besides server name in server selection

reddit/assets/reddit.html, reddit/plugin_web.go
To disable and not just to delete a Reddit feed has been requested several times... Looking at the back end of reddit code, it looks like nothing dramatical needs to be changed; None/0 channels in database are already avoided and disabled. So this little change enables front-end possibility for users to disable their feed.
=> Reddit: disable feeds option

customcommands/tmplextensions.go
Added:
dbDelMultiple - deleting multiple entries 
dbRank - finding rank according to a custom query (very helpful with leader board implementations, I have tested this upto 3 million entries for a given server and it took 3-5s at max even at this scale. dbCount is also equally slow at this scale.)
dbCount improvement.
=> CC database - new functions and improvements

automod/automod_web.go, customcommands/customcommands.go, notifications/plugin_web.go, premium/plugin_web.go, reputation/plugin_web.go, stdcommands/poll/poll.go, twitter/web.go, web/handlers_auth.go, web/middleware.go, web/validation.go, web/validation_test.go, web/web.go
As title states. Often requested on the server and I see no reason not to enable this command's slash alternative.
=> stdcommands/poll: enable slash command

frontend/templates/cp_selectserver.html, frontend/templates/index.html
Removes old information about additional payment methods and ad spaces, edits the guild join card to show the link to the docs instead of saying they're incomplete, fixes general wording.
=> frontend/templates: remove old information

premium/assets/premium.html
This PR removes information about stats retention which isn't a thing anymore, while also making slight changes to the wording.
=> premium/assets: remove invalid information

README.md
Because I'm a newbie, and didn't know that was a thing. So someone else might need to.
=> Point people at CONTRIBUTING.md

moderation/commands.go
=> Appropriate plural in the purge success message

common/templates/context_funcs.go, common/templates/general.go
Continuation of #963, but with a few more ones that were missed.
This should be all, I checked through all the code in templates/ that might be affected and there's nothing else that might pose an issue as far as I see.
Works as expected on selfhost.
=> templates: indirect more values

notifications/plugin_bot.go, verification/verification_bot.go
=> verification/join msg: make DMs carry server data

frontend/templates/cp_logs.html
Changed the name of the current developer
=> Name change of developer in cp_logs.html

antiphishing/antiphishing.go, antiphishing/backgroundworkers.go, automod/rulepart.go, automod/triggers.go, automod_legacy/assets/automod_legacy.html, automod_legacy/rules.go, cmd/yagpdb/main.go
In this PR I've added protection for common scam links 
They can be enabled by a single click in Basic Automoderator, or can be configured via a trigger in AMV2
=> Added antiphishing protection

.github/workflows/action.yml
Hey there!
The old workflow was broken (my fault really) -- this pull request fixes it.
=> workflows: fix it for good

antiphishing/antiphishing.go, automod/triggers.go, automod_legacy/assets/automod_legacy.html, autorole/assets/autorole.html, commands/assets/commands.html, common/templates/context.go, customcommands/assets/customcommands-editcmd.html, customcommands/customcommands.go, customcommands/interval.go, frontend/static/vendorr/bootstrap/css/bootstrap.css, moderation/assets/moderation.html, moderation/modlog.go, reddit/assets/reddit.html, reputation/assets/reputation_settings.html, rolecommands/assets/rolecommands.html, streaming/bot.go, verification/assets/verification_control_panel.html
- Better checks in AntiPhishing.go
- Fixed a few AMV2 triggers 
- Added Min and Max times on intervals 
- Limited length of string outputs
=> A lot of minor fixes

automod/automod_web.go
Old suggestion on the support server. Effect is simple:
if no mute role is setup, but the "mute user" effect is selected
as an amV2 rulepart, error out and nudge user to set one up.
Works on selfhost fine, as far as I can tell:
Simply create the required boilerplate for an amv2 rule, create one with the "mute" effect while no mute rule configured.
=> automod/web: warn user if no mute role is set up

automod/assets/automod.html, automod/automod_web.go
=> automodv2: support editing list names

twitter/assets/twitter.html
This PR fixes the action url for twitter control panel form from reddit to twitter.
=> Fix form action url for twitter control panel

antiphishing/antiphishing.go, common/util.go
Fixed domain checker regex to be case insensitive, and also converted the final detected domain to lowercase.
=> added fixes for making domain finder regex case insensitive

antiphishing/antiphishing.go, common/util.go
Improved link and domainfinder regex.
=> Hotfix for Twitch.tv being banned by antiphishing.go

go.mod, go.sum, streaming/bot.go
- rolled back template version 
- changed logging ignoring bots for streaming role as error to info to reduce spam in logs.
=> Rolled back template version 

go.mod, go.sum, stdcommands/calc/calc.go
This PR fixes incorrect dependencies in #1131
=> Fix dependency issues created in #1131

reminders/plugin_bot.go
Same as #1008, conflicts were solved
=> Add codeblock to command response

soundboard/player.go
While I have tested this change fairly thoroughly, the soundboard code is quite complicated due to it being concurrent, with many possible paths through the code. I am not fully certain that this patch does not introduce new race conditions as I am unfamiliar with the surrounding code. Further testing under different scenarios (i.e., multiple servers using soundboard) would be appreciated.
---
When a user runs soundboard in a voice channel — but not the one the bot is in — it is expected that the bot switches voice channels when the sound played comes up. This does not occur currently -- the bot does not change channels with the user, though the code is written with the intention to do so.
<details><summary>Reproduction steps</summary>
1. Have two voice channels. We will refer to them as …
=> soundboard: actually switch voice channels

.circleci/config.yml, autorole/assets/autorole.html, autorole/autorole.go, autorole/bot.go, common/scheduledevents2/backgroundworker.go, common/scheduledevents2/scheduledevents.go, go.mod, verification/verification_bot.go
Members were being assigned roles from Autorole even if their membership screening was pending.
This PR adds a toggle to make membership screening required before assigning autrole to that member.
=> Update autorole to add Membership screening required toggle, and add its handling

go.mod, go.sum
Full changelog: 
https://github.com/botlabs-gg/template/compare/v1.1.3...v1.1.4
=> Bumped template version to v1.1.4

autorole/autorole.go, autorole/bot.go, verification/verification_bot.go, verification/verification_web.go
This feature release in v1.32.0 was causing too many GetMember calls to Discord, while just getting them for the State was necessary.
=> improvements to memberscreening autorole

stdcommands/dadjoke/dadjoke.go, stdcommands/stdcommands.go
This command uses an API (icanhazdadjoke) to pull in a random dadjoke. 
I had contacted the original creator of this code to get it re-done. They had confirmed to me it still worked and they used it on their self-host. I have tested the code on my own self-host now.
=> add dadjoke command.

reddit/assets/reddit.html, reddit/plugin_web.go, twitter/assets/twitter.html, twitter/web.go, youtube/assets/youtube.html, youtube/feed.go, youtube/web.go, youtube/youtube.go
This PR adds toggles to enable/disable the feeds on the config pages for Youtube, Reddit and Twitter.
=> Add toggle on the feeds list to enable/disable the feeds

rolecommands/web.go
- When adding new role commands, place them at the end instead of the front, which is more intuitive (an old suggestion for changing this behavior got 29 votes for and none against.) The change is not retroactive; the order of role commands added before the change are not affected.
- Add the name of the role group to the duplicate role command error to help out the user in case they wish to delete it.
=> rolecommands: improve ui

automod/effects.go
Users have mentioned this and it is a reasonable request - to be able to auto-delete the sent amV2 effect's message. Currently the max duration to delay the deletion is 1 hour (0 does not delete the message) and this max duration is open for discussion.
=> AMv2 effect delete sendmessage

customcommands/tmplextensions.go, lib/dcmd/arg.go, reputation/plugin_bot.go
Updated UserArg in dcmd to accept the user id.
Use dcmd.User in all places in reputation related commands for consistency.
=> Update User arg in dcmd to accept ID, use this in all rep related commands

frontend/templates/status.html
This shows a refresh timer, and refreshes the page every 30 seconds.
=> added autorefresh to status page

reputation/plugin_bot.go
Add a `-user` flag for toprep that begins the leaderboard with the users around the rank of the given user.
Works fine on selfhost as far as I could tell.
=> reputation: -user flag for toprep

common/templates/context.go
.BotUser makes it easier to get YAGPDB's ID or any other reference to bot user in custom commands.
=> templates: .BotUser to context data

frontend/static/css/custom.css, reddit/assets/reddit.html, twitter/assets/twitter.html, youtube/assets/youtube.html
This PR adds links to added subscriptions for Reddit, Twitter, YouTube feeds. Makes it easier for example to debug feeds, is it the correct one, etc. 
Extra addition for Reddit is `r/` before subreddit's name.
=> Feeds QoL: links to added feeds

frontend/templates/index.html, yagpdb_docker/docker-compose.dev.yml
And made https=false as default in dev dockercompose.
=> added support server url to header to make it easier for people to join. 

automod/db_schema.go, stdcommands/inspire/inspire.go, stdcommands/stdcommands.go
Inspirational quotes from inspirobot.me.
=> stdcommand: inspire

automod/effects.go, bot/paginatedmessages/pageinatedmessage.go, bot/paginatedmessages/paginatedinteractions.go, commands/slashcommands.go, commands/util.go, common/mqueue/discordprocessor.go, common/templates/context.go, common/templates/context_funcs.go, common/util.go, lib/dcmd/arg.go, lib/dcmd/container.go, lib/dcmd/data.go, lib/dcmd/parse.go, lib/dcmd/response.go, lib/discordgo/components.go, lib/discordgo/interactions.go, lib/discordgo/locales.go, lib/discordgo/message.go, lib/discordgo/restapi.go, lib/discordgo/structs.go, lib/discordgo/utils.go, moderation/commands.go, notifications/plugin_bot.go, stdcommands/simpleembed/simpleembed.go
This PR
1. Adds structs and functions required for interactions.
2. Updates paginated messages to use interaction buttons instead of reactions.
=> Add interaction related structs and functions, use buttons in paginated commands

frontend/static/css/theme.css, logs/assets/logs_view.html
=> Update popover header color and fix popover not closing

youtube/assets/youtube.html, youtube/feed.go, youtube/web.go, youtube/youtube.go
=> Added support for all youtube urls 

automod/conditions.go
When the checkbox is checked, then the member needs to have all the selected roles in order to satisfy the condition for the AMV2 rule.
=> Added toggle to require all roles for amv2 condition `Require roles`

rsvp/plugin_bot.go, rsvp/rsvp.go, rsvp/setup.go
=> Added interaction buttons in rsvp events

stdcommands/wouldyourather/wouldyourather.go
A raw switch for wyr, returns options as text... useful for custom commands exec functions.
=> stdcommands: wouldyourather raw switch

bot/botrest/server.go, bot/nodeimpl.go, lib/discordgo/events.go, lib/discordgo/gateway.go, lib/dshardorchestrator/cmd/dso-sample-bot/node-implementation.go, lib/dshardorchestrator/eventstructs.go, lib/dshardorchestrator/node/interface.go, lib/dshardorchestrator/node/node.go, lib/dshardorchestrator/tests/basic_test.go, lib/dshardorchestrator/tests/fullmigration_test.go, lib/dshardorchestrator/tests/mocknode.go
Ref: 
https://discord.com/developers/docs/change-log#sessionspecific-gateway-resume-urls
=> Added support for  resumeGatewayUrl for resuming gateway sessions 

common/templates/context_funcs.go
enables reply-ping for sendMessageNoEscape, that in mind... editMessageNoEscape needs some overview in the feature
=> Reply-ping for sendMessageNoEscape

cah/plugin_bot.go, lib/cardsagainstdiscord/cmd/cardsagainstdiscord/main.go, lib/cardsagainstdiscord/game.go, lib/cardsagainstdiscord/manager.go, lib/discordgo/interactions.go
Card selector in DM
Winner selection
=> Added interactions in CAH game

common/templates/context.go, common/templates/general.go
Unmarshals given JSON to templates.SDict. sdict is commonly used and also useful for cembed.
=> templates: jsonToSdict

automod/conditions.go, automod/triggers.go
I came across some wording inaccuracies. This makes those inaccuracies no longer inaccurate.
=> Amv2 fix trigger hint text

common/templates/general.go
Presently, to print out the contents of a slice containing strings using `joinStr`, one has to call `StringSlice`:
```
{{joinStr " " (cslice "a" "b" "c")}} {{/* no output */}}
{{joinStr " " (cslice "a" "b" "c"}} {{/* a b c, as desired */}}
```
From the perspective of a user, it's rather unintuitive that one has to call `StringSlice` to get the desired output; if the slice already contains strings, why the conversion? (The answer, of course, is that a slice is backed by a `[]interface{}` which is not technically a string slice, but this requires knowledge of implementation details which should not be the case.) This PR fixes this minor pain point by making `joinStr` convert slices to string slices automatically as needed.
=> templates: make joinStr automatically convert to str slice

moderation/commands.go
Make `clean` ignore the triggering message, so `-cl 5` will remove 5 messages -- as opposed to 4 messages plus the trigger -- from the perspective of the user.
=> moderation: make clean consistently ignore trigger msg

common/mqueue/discordprocessor.go, reminders/reminders.go
=> Moved reminder message to embed description

common/templates/context_funcs.go, lib/dcmd/container.go, lib/discordgo/structs.go, web/template.go, web/web.go
and also added support for threads in announcement channels for custom commands.
=> Added support for forums channels to be selected in channel selectors 

reddit/redditbot.go, twitter/feed.go
=> Changed webhook usernames for twitter and reddit feeds. 

reddit/redditbot.go
=> Changed reddit footer to not have upvotes and downvotes in fast feeds. 

stdcommands/exchange/exchange.go, stdcommands/forex/forex.go, stdcommands/stdcommands.go
This command was made by Shadow and Mr. Ben, but shadow doesn't know how to use git, so I am pull requesting it for him. 
Co-Authored-By: Shadow <66721908+Shadow21AR@users.noreply.github.com>
=> Added exchange.go 

stdcommands/inspire/inspire.go
😭 finally ....
Modified the inspire.go to have text paginated output.
=> modified inspire.go

stdcommands/throw/throwthings.go
Added "beans" to things to throw
=> Added another thing to throw

reputation/plugin_bot.go, tickets/tickets_commands.go
Updating the rep and tickets system with links to their config pages in the control panel, when they error out because the system is disabled.
=> Config page links

logs/assets/logs_control_panel.html, logs/web.go
- added note for log purge. 
- "newer" and "older" links have a margin between them
=> ui fixes for logs page

common/templates/context_funcs.go
The old sort function was rather clunky to use for two reasons:
- Input of mixed types was accepted, but produced unintuitive output: `sort (cslice -1.1 1 2 3)` resulted in `[1 2 3 -1.1]`;
- More advanced use-cases (such as sorting by the value of a key in a map value) were not supported.
This PR attempts to address these issue. In particular, the new implementation:
- Rejects input of mixed types, as it is indicative of a user error;
- Allows for sorting by a key, so `sort (cslice (sdict "name" "bob") (sdict "name" "alice")) (sdict "key" "name")` just works;
- Removes the `subslices` and `emptyslices` options, which have unclear purpose but require a substantial amount of code.
It must be noted that **this PR is a breaking change.** However, the `sort` function is not widely used, …
=> templates: rewrite sort function

lib/dcmd/arg.go, stdcommands/forex/forex.go
Adds support for float input to forex
Before:
After:
=> forex: float support

logs/plugin_bot.go, logs/template_extensions.go, logs/web.go
- Disabled nickname and username commands if the logging is disabled. 
- Hidden from home widget 
- disabled respective templates 
- fix condition for queuing event for logging
=> fixed bugs and inconsistencies related to username logging

youtube/feed.go, youtube/youtube.go
This theoretically should make youtube a lot more reliable as right now the issues seem to be delayed subscriptions.
=> divided youtube subs into chunks and processing each chunk in parallel using go routines

youtube/feed.go
- Added sleep of a second to let go routines go brrrrrr on large bots. 
- Removed lock for subs out of the loop.
=> More improvements to youtube websub logic

stdcommands/inspire/inspire.go
new flag on inspire commanf for XMAS season.
Screenshot to show it gives images related to xmas:
=> Update Inspire command, added `season` arg for season variants of response! (xmas)

customcommands/tmplextensions.go
This reverts commit a6b34de67d1310070235294a4fc9163274acf390.
=> Revert "templates: add support for switch args w/ parseArgs (#893)"

stdcommands/throw/throwthings.go
added 'a discord channel' to list of things to throw.
=> added 'a discord channel' to list of things to throw.

youtube/feed.go
- Added support for publishing upcoming live videos 
- Added more metadata to custom feed context
=> Upcoming videos and more metadata added

youtube/assets/youtube.html, youtube/feed.go, youtube/web.go
and fixed a bug with custom urls not working
=> added support for youtu.be urls 

customcommands/bot.go, reminders/plugin_bot.go, streaming/bot.go
+ disable execAdmin to create reminders on yagpdb
=> Stop reaction CCs from executing on bots

common/templates/general.go
Currently, if a user passes conflicting values to allowed_mentions in complexMessage, for instance passing "users" to the "parse" argument, then passing IDs to the "users" field, the message will silently fail to send, seemingly due to the fact that these conflict (see below)
This pull request will cause the command to error if this is done (see below)
=> customcommands: add error to parsemessagementions for conflicting values

lib/discordgo/user.go, logs/plugin_bot.go
and removed some commented code.
=> added global_name to user object

logs/backgroundworkers.go
=> added warning log link deletion too from warnings older than 30 days

premium/assets/premium.html
This PR is regarding to improve UI of website. 
Before:
After:
=> Update: bottom margin added in redeem code input box

automod/automod_bot.go, automod/rulepart.go, automod/triggers.go, bot/bot.go, lib/discordgo/events.go, lib/discordgo/gateway.go, lib/discordgo/structs.go
Code has been tested but I'm not 100% sure it's free of bugs. Please lmk if you spot anything
=> Discord automod trigger

moderation/commands.go, moderation/plugin_bot.go, moderation/tmplextensions.go, moderation/topwarnings.go
Added a from flag in clear command, it acts as a start message for clear to work
=> added a -from flag in clear

reddit/plugin_web.go
fixed a bug where reddit feed counts would be shown incorrectly on se…rver home if there were no slow feeds
=> Reddit Feed count bug fix

automod/automod_bot.go
Fixes discord's stupid automod sending event several times. See [here](https://canary.discord.com/channels/166207328570441728/384011387132706816/1137801255616516096) for context
=> Discord Automod patch

automod/conditions.go, automod/rulepart.go
This PR satisfies [this suggestion](https://canary.discord.com/channels/166207328570441728/356486960417734666/870933165726900275)
=> AMv2 ignore / active in threads condition

web/template.go
Show deleted channels in dropdowns, and while at it, refactor the code generating the dropdown HTML for improved clarity as it was rather difficult to follow previously. (No visual changes other than the inclusion of deleted channels — see `outputDeletedChannels`, which has no counterpart in the existing code — have been made.) The refactor consists primarily of introducing a helper structure `channelOptsHTMLGenState` and then moving parts of the existing implementation into methods of this new structure. This provides much clearer organization of the various steps of the HTML generation process compared to before.
Not showing deleted channels (the current behavior) results in a difficult-to-diagnose visual bug, which can be reproduced as follows:
1. Create a new channel, say `#foo`.
2. …
=> web: display deleted channels in dropdowns

bot/discordevents.go, common/templates/context.go, common/templates/context_funcs.go, lib/discordgo/restapi.go, notifications/plugin_bot.go, verification/verification_bot.go
Replaced text in message content / embed footer in DMs with a link button as it is done across other popular bots on discord, making dms look cleaner. 
The link button  takes the user to the server and has the name of the server
=> Replaced Text in content and footer with Link button for DMs

stdcommands/forex/forex.go
API changed to [Frankfurter](https://www.frankfurter.app/), It is a free and open-source currency data API (yeah they claim this on their GitHub)
it gives most of the used currencies. 
here's a pic to make my message look bigger
=> changed to another API cuz old one is paid now :<

customcommands/assets/customcommands-database.html, customcommands/customcommands.go, customcommands/web.go, logs/web.go
- Pagination Buttons work now with search 
- Pagination buttons are now hidden on first and last page appropriately
- Search data is persistent on the page and doesn't get reset with each search
=> Improvements to db page search

cmd/yagpdb/sampleenvfile
I found this while I was setting up the project.
It is wrong unless I misunderstood.
=> Fix typo in sampleenvfile

stdcommands/topservers/topservers.go
pushing a free PR. Changed category of the `topservers` command, also added `*Bot Admin only` to the help description to clarify
=> Clarification of topservers command

stdcommands/cleardm/cleardm.go, stdcommands/stdcommands.go
This deletes upto 100 DM messages sent by the bot.
=> Added a Bot Owner Only,  Clear DM Command. 

customcommands/assets/customcommands-editcmd.html, customcommands/assets/customcommands-public.html, customcommands/web.go, frontend/static/css/theme.css
- Separated public CC into a separate template and controller. 
- Made UI less clunky 
- Fixed legacy issues like lengths for trigger, name, and cc not showing on page load. 
- Fixed broken header on tablet ui.
=> Refactored the Public CC page, and did some UI fixes for old issues. 

stdcommands/viewperms/viewperms.go
Implement suggestion 2213: let users specify a target channel for `viewperms` via the `-channel` flag, e.g., `-viewperms @bob -channel #lounge`.
=> viewperms: support specifying target channel

common/templates/context_funcs.go
* Allow tag IDs to be provided as well as names
* Allow closeThread flag to be false
* Allow editThread to edit tags
=> cc/threads: hotfix

common/common.go, common/loghooks.go, common/util.go, go.mod, go.sum
Following #1668, we can pull out gorm entirely.
=> all: remove last traces of gorm

customcommands/assets/customcommands-editcmd.html, customcommands/bot.go, customcommands/customcommands.go, customcommands/models/custom_commands.go, customcommands/schema.go
You can select a channel to which you want to redirect CC error messages.
Suggestion Message Link: [Boop](https://discord.com/channels/166207328570441728/356486960417734666/1052684926014734427)
https://github.com/botlabs-gg/yagpdb/assets/58076174/6b6c9c71-d9df-44b0-8da2-723438729ce4
=> Redirect CC errors to selected channel [Suggestion #2023]

customcommands/assets/customcommands-editcmd.html, customcommands/assets/customcommands.html, customcommands/schema.go, customcommands/web.go
=> Fixed confusing UI for CC Group disable toggle. 

customcommands/bot.go
Currently, `exec` and `execAdmin` do not work as expected (often resulting in runtime panics) when triggered from an interaction on an ephemeral message.
<details>
<summary>Click to expand reproduction steps</summary>
(For convenience, the necessary custom commands can be imported as https://yagpdb.xyz/cc/olWroLOPY0 and https://yagpdb.xyz/cc/ecfP_ypYhY.)
1. Create a custom command `-bug` that replies with a button:
```
{{ sendMessage nil (complexMessage "buttons" (cbutton "label" "Click me!" "custom_id" "clickme")) }}
```
2. Create an interaction custom command `clickme(_ephemeral)?` that replies with an ephemeral message containing another button when the previous button is clicked; and triggers `exec "whois" .User` when this ephemeral button is clicked:
```
{{ if in .CustomID …
```
=> cc: fix tmpl exec on ephemeral context messages

README.md, automod/assets/automod.html, automod_legacy/assets/automod_legacy.html, commands/help.go, customcommands/assets/customcommands-editcmd.html, frontend/templates/cp_main.html, frontend/templates/cp_nav.html, frontend/templates/cp_selectserver.html, frontend/templates/index.html, moderation/assets/moderation.html, stdcommands/customembed/customembed.go, youtube/assets/youtube.html
=> Updated the links to point to new docs, and changed youtube custom notification text. 

bot/memberfetcher.go, common/templates/context.go, common/templates/context_funcs.go, lib/discordgo/endpoints.go, lib/discordgo/restapi.go
=> added getMemberVoiceState, it gets the voice state of a specific member in the server. 

moderation/commands.go
Previously, clean and reason command would return an error implying that
they had configurable additional roles similar to kick, ban, warn, and
mute. This commit changes that so only the commands which do have this
config available will mention it if a user tries to use the command without
the required permissions.
=> moderation: clarify permission error

go.mod, go.sum, stdcommands/undelete/undelete.go, yagpdb_docker/Dockerfile
and also bumped go version to 1.23
=> added discord timestamps to undelete

stdcommands/undelete/undelete.go
Because people keep asking for "snipe"
=> added -count flag to undelete

moderation/commands.go
Since this limit is hard-coded into the bot, it is reasonably considered a bot limitation and should therefore be  documented.
=> mod/cmd: update clean desc include age limit

automod/sqlboiler.toml, bot/sqlboiler.toml, commands/sqlboiler.toml, common/scheduledevents2/sqlboiler.toml, common/sqlboiler.toml, customcommands/sqlboiler.toml, logs/sqlboiler.toml, moderation/sqlboiler.toml, notifications/sqlboiler.toml, premium/sqlboiler.toml, reddit/sqlboiler.toml, reminders/sqlboiler.toml, reputation/sqlboiler.toml, rolecommands/sqlboiler.toml, rsvp/sqlboiler.toml, serverstats/sqlboiler.toml, soundboard/sqlboiler.toml, tickets/sqlboiler.toml, timezonecompanion/sqlboiler.toml, twitter/sqlboiler.toml, verification/sqlboiler.toml, youtube/sqlboiler.toml
user="yagpdb"
pass="ihateducks"
=> made the sqlboiler.toml files consistent between all plugins

common/templates/context_funcs.go
In https://github.com/botlabs-gg/yagpdb/pull/883, we consolidated the role functions so that they all call `FindRole` under the hood, which accepts role IDs, role mentions, role names, and role objects. However, this change introduced a minor regression--it eagerly resolves inputs in the order above--so a string such as `"1"` will always be interpreted as a role ID instead of a role name (and thus never resolve to the role named `1`, if it exists.) This scenario is admittedly degenerate, but we have gotten the occasional complaint about broken code from servers using numerical role names with `addRoleName` and similar.
In this PR, we try to fix the above issue by allowing to restrict the types of input `FindRole` accepts and adjusting the role functions accordingly. So, for example, …
=> templates: be stricter with accepted role inputs

bot/bot.go, lib/cardsagainstdiscord/cmd/cardsagainstdiscord/main.go, lib/discordgo/gateway.go, lib/dstate/example/main.go
This lets us receive guild emoji updates and update the cached Emojis fields accordingly.
=> bot: declare guild emojis intent

tickets/tickets_commands.go
This PR sets the `MenuCreate` command to require the `MANAGE_GUILD` permission.
=> tickets/ticket_commands: restrict MenuCreate command to ManageGuild

moderation/commands.go
I like sometimes to delete bot message only.
Just filters if messages are sent by a bot.
=> add -bots switch to the clean command

stdcommands/roast/roast.go
since the roast command now posts a fancy embed, I wanted to add a -raw flag to pull the roast out without the embed object
[tested ok](https://nc.randomdad.xyz/s/8r25nsA8j6RxZrJ/preview)
signed off by savage4618
=> adding -raw flag

automod/automod_bot.go, automod/rulepart.go, automod/triggers.go
Username based triggers are kind of useless ever since discord moved to the new pomelo system.
=> Replace username triggers with globalname triggers

common/templates/context.go, common/templates/general.go
=> templates: add absolute math operator

common/templates/general.go
=> templates: add suppress embeds to complexMessage(Edit)

rolecommands/commonrole.go
=> rolecommands: elaborate on cooldown message

bot/paginatedmessages/paginatedinteractions.go, common/templates/context.go, common/templates/context_funcs.go, common/templates/context_interactions.go, common/templates/general.go, lib/cardsagainstdiscord/game.go, lib/cardsagainstdiscord/manager.go, lib/dcmd/data.go, lib/discordgo/components.go, lib/discordgo/interactions.go, lib/discordgo/message.go, lib/discordgo/structs.go, notifications/plugin_bot.go, rsvp/plugin_bot.go, stdcommands/xkcd/xkcd.go, tickets/tickets_bot.go, tickets/tickets_commands.go, trivia/trivia_bot.go
Apparantly this doesn't work very well with interactions, reverting for now. 
Reverts botlabs-gg/yagpdb#1879
=> Revert "discordgo: add v2 components"

rss/assets/rss.html, rss/feed.go, rss/web.go
- Fixed UI bugs 
- Improved formatting for feed messages 
- Improved deduplication logic.
=> More Fixes for RSS Feeds 

autorole/autorole.go, autorole/bot.go, autorole/web.go, bulkrole/assets/bulkrole.html, bulkrole/bot.go, bulkrole/bulkrole.go, bulkrole/web.go, cmd/yagpdb/main.go, frontend/static/css/theme.css, frontend/templates/cp_nav.html, premium/plugin_web.go, rolecommands/web.go, tickets/tickets_web.go, web/template.go, web/web.go
Based on Retroactive Role Scan in Autoroles
Bulk Roles is a premium only feature that assigns bulk roles based on the specified set of filters.
=> Added Bulk Roles

reputation/plugin_bot.go, reputation/reputation.go
(Obviously this is not premium)
=> change thanks rep to give rep to all mentioned users in the message

frontend/static/css/custom.css, frontend/templates/cp_nav.html, frontend/templates/index.html, personalizer/assets/personalizer.html, personalizer/web.go, premium/assets/premium-perks.html
- Makes banner preview the same size as discord 
- Makes avatar larger
=> minor enhancements to personalizer ui

customcommands/assets/customcommands-editcmd.html, frontend/static/js/spongebob.js, notifications/assets/notifications_general.html
The response was being deleted even after clicking cancel.
=> Fixed response deletion prompt for custom commands and general notification. 

bot/bot.go
=> Added caching to max concurrency fetch when reconnecting shards. 
