botlabs-gg/yagpdb

common/templates/context.go, common/templates/general.go
I have no immediate use for this functionality. I was using this to more effectively make use of .Args in command templates, but the new .CmdArgs serves my needs with far less effort. I offer it here only in case you think it might be useful at some point.
Example use:
{{slice .Args 1 | addReactions}}
=> Add new template func "slice" for creating sub-slices

cmd/yagpdb/static/css/landing-page.css
For small devices, I was playing around with it recently and forgot to set it back to a reasonable value.
=> Fixed font size

stdcommands/currentshard/currentshard.go
"CurentShard" changed to "CurrentShard"
=> typo fix in currentshard.go

common/util.go
Blocked discord.io links as they provide 3rd party vanity invite urls
=> Block 3rd party invites

automod/conditions.go, automod/rulepart.go
I mocked up this change for a feature that would be useful on my server. I have not yet been able to run/test this code but I saw that my suggestion got pinned on the server and if this helps to get it implemented faster I hope I can save the dev team's time.
Hopefully it's on the right track and doesn't need too much change in order to be implemented/useful.
=> Add 'ignore edited messages' condition to automod v2

autorole/bot.go
Capitalized Roledb as all other commands under that help category are capitalized.
=> Consistency Fix

common/templates/context.go, common/templates/context_funcs.go
This request adds the functions targetHasRoleID and targetHasRoleName, allowing for custom commands that can check any user's role information, rather than being specific to the user who called the command.
=> Adds targetHasRoleId and targetHasRoleName functions

customcommands/bot.go
This is temporary fix ( and reminder : ) for displaying the list of custom commands and if custom command's trigger text is left empty (typically by choosing interval trigger type). It will not mess the list with ` characters.
=> temporary fix bot.go

moderation/commands.go
This help clarification confuses people, they think ID is from warning's ID not modlog's messageID.
=> ID to Message ID

commands/assets/commands.html
This is just a one word on the cmd settings page as it might help with some of the silly things people type
Also changed the value of the text field if empty to Prefix (type before all commands)
=> Change prefix to Command Prefix

moderation/assets/moderation.html
Allow users with the following roles to use the mute commands > Users with the following roles will have permission to use mute related commands Etc.. (basically just adding that it allows permission instead of actually allowing users to use the commadns to stop them from being confused with the channel/command overrides)
=> Better moderation.html wording kbye

rolecommands/web.go
Rolecommands plugin has two limits, rolecommands and rolegroups count, they both are capped, It would be more informative to present both of these counts. Dunno whether on not to manually write that current max 1000 there or not,
=> usability suggestion for control_panel combined overview

moderation/commands.go
You cant use mod commands on users ranked the same or higher than you, changed the message to be accurate instead of saying "higher" it now says "the same as or higher"
=> Update string to reduce confusion

rsvp/plugin_bot.go
Changed to 🎟 from 🎫 as its not used like the other ticket and its an "admit one" ticket for ios
=> Rsvp help emoji

common/templates/general.go
This type case was missing and actually necessary, because indexing a string creates uint8.
=> uint8 added

yagpdb_docker/docker-compose.dev.yml, yagpdb_docker/docker-compose.yml
The only method to migrate data between major Postgres vesrions is a backup and
restore. This provides no clean path for users to rebuild their server so let's
pin the version to reduce surprises.
Although version 10 was current when this config was originally checked in,
version 11 has been the latest for 9 months and I am assuming more users are
using that "latest".
With version 12 coming out soon, it seems like a good time to resolve this
problem
For users discovering this commit message that wish to upgrade, the following
gist can be useful:
https://gist.github.com/LoganK/7ceb1506102f5d469556c69620a3d1c2
(Remember to change your volume name in your docker-compose file.)
=> Docker: Pin Postgres major version

common/templates/context.go, common/templates/general.go
This was discussed today in # custom-command-discussion channel, albeit it's doable without specific function, maybe this one is simpler for users. I omitted nanoseconds and also *Location - left it as UTC.
=> toTime function for templates (name changed newDate)

logs/plugin_bot.go, reputation/plugin_bot.go, stdcommands/topservers/topservers.go
Due to the adding of paginators in version 1.20, there is no longer a limit for the commands.
For the topservers command, it shows 20 servers and not 15.
=> Update command descriptions

customcommands/assets/customcommands.html
the colon between .TriggerType and .TextTrigger already helps to separate default text better and increases readability. 
I added <span> for users who want to alter CSS styling further on their side - I know it deviates from bootstrap styling, but that <span> does not kill anything : )
=> slight changes in presenting custom commands

common/templates/context.go, common/templates/context_funcs.go
users have mentioned the need for this, it's blunt force removal - not specific to reactionName or userID, but maybe necessary
=> Function to delete all message reactions

common/templates/context.go, common/templates/general.go
Although it can already be done using current custom command functions, "real" square root is still more reasonable. I used type switching to get always NaN answer if not a number instead of 0.
=> square root function

cmd/yagpdb/templates/cp_main.html
Notifies users of potential problems with Discord servers to assist in troubleshooting issues with the bot.
=> Add Discord status alerts to dashboard

customcommands/assets/customcommands.html
was wondering why I left the  white-space there in front of colon for regular command names... because of Inteval trigger! But this solution might be better > Interval: Every... and IntervalEvery is prevented : )
=> trigger name - whitespace before colon update

timezonecompanion/plugin_bot.go
Self explanatory, all the aliases for toggletimeconversion are pretty long, it would be nice if there were a shorter alias such as ttc.
=> Add ttc as alias for toggletimeconversion

rsvp/plugin_bot.go
Replaces `findUserWithNickname()` with `findUsers()` which doesn't use nicknames. This makes things less ambiguous as to whether the bot is using username + discrim or nickname + discrim.
=> RSVP shouldn't use nicknames

common/templates/context.go, common/templates/context_funcs.go
Added a new template to allow editing nickname of the user triggering a command. Editing nicknames are a very popular request however ability to edit nickname of any target user has misuse potential . Hence , implemented it to only work on triggering user similar to sendDM. 
Introduced a new checker "edit_nick" which allows only two calls per cc instance similar to tmplEditChannelName . 
Also, tried to save unnecessary API call if present nickname is already same as new nickname.
=> Satty9361 edit nickname template

moderation/punishments.go
Dont send DM if response only consists of whitespace. This can also be used to smartly disable ban/mute/unmute/kick/warn DMs while still allowing to do any kind of processing like maintaining Records in database upon Mod Action that the user wants to do.
=> Small update to not send blank DMs when response only consists of whitespace for Punishments.

serverstats/serverstats.go
currently database table server_stats_member_periods does not have column "started", changed it to created_at and added also err check. Stats command for bot and also web page shows joined/left users, memberCount now.
=> slight bugfix in ServerStatsMemberPeriods query

common/templates/context.go, common/templates/context_funcs.go
Users have requested for this. It is already possible with execCC with channelID followed by .Channel, this makes the process less convoluted. 
The lock argument in ChannelCopy should probably be false ? ( since ChannelArg already has a Rlock) however tmplRunCC has lock set to true hence i have kept it as true for now.
=> getChannel template

common/parseduration.go, common/templates/general.go
due to import cycles with ../commands/, templates directly can not use util.go and it's ParseDuration function. That's why I suggest duplicating that code to common - could also be directly copied to, let's say templates/general.go, but at this point I preferred to keep it separate.
Users really want to have duration conversion also in string form "1w1h", changed the ToDuration function.
=> Duration parsing

automod/commands.go, bot/paginatedmessages/pageinatedmessage.go
Pagination Error Patch : When specifying a page number in paginated messages and there is no result, it displays the following error : 
> "Something went wrong when running this command, either discord or the bot may be having issues."
It also causes custom commands to stop execution due to error generation. This is an idea to fix this behavior. With above changes, error will not be generated during first run. Max page is also appropriately updated when going to a lower page with a simple change in paginatedmessage.go . Same method can be adopted in other paginated commands that allow specifying page like amod logs.
Pictorial Representation : left button -> left button -> left button -> right button.
Other Changes : 
Added a Total field to ListViolationsCount
Typo fix /n -> \n and …
=> Pagination Error , typo & other fixes/additions

commands/util.go
HumanizeDuration returns string, so if ever this error happens, let it be correct one : )
=> small typofix

commands/tmplexec.go
made these changes so that an exec/execAdmin following an execCC runs in the new channel. 
Have not incorporated channel update for dm templates ( eg: punishment dm templates) to prevent loops (eg: warn -> warn dm execCC -> execAdmin warn ...) .
=> exec/execAdmin with execCC fix

customcommands/tmplextensions.go
This might be a typo, because stringedKey value is of type string and database query wants BIGINT. Still works at present state if user presents the "key" as integer - or is this intentional?
=> possible typo fix on database query type

common/templates/context_funcs.go
targetUserID can handle mentions and getMember uses targetUserID instead of direct ToInt64.
=> QoL changes

moderation/commands.go
Fix "clean" command bug deleting extra message in some cases with exec/execAdmin .
Refer [#bugs](https://discordapp.com/channels/166207328570441728/214439334089195521/663612392499970058) for details. 
Caused because num was increased even in cases there is no real message triggering the command directly.
=> Clean BugFix

customcommands/bot.go
Have seen users wanting this, could be useful info outside control panel, so why not add it to the custom commands dot. That +1 is there to count current "launch" as well.
currently users implement their CCcounters through database, so it lessens that a little.
=> addition: .CCRunCount

moderation/commands.go, moderation/topwarnings.go
Command that will give ranked list of all guild's user warnings, does not create a web-based listing - not necessary for mod commands. Also, currently kept the additional function and type in separate file because really can't find better place to add the code to, maybe plugin_bot.go
=> Idea: moderation command TopWarnings

common/templates/general.go, customcommands/assets/customcommands-editcmd.html, rolecommands/assets/rolecommands.html, rolecommands/web.go
This here includes HTML code (without any additional CSS styling) for delete button, which is displayed if there are role commands set in a group + counter of rolecommands in that group. 
HandleDeleteRoleCommands, when invoked will delete the rolecommands only from within that group, group itself still remains there. Also deleting from Ungrouped is possible.
Should not be database heavy.
=> Idea: Delete Role Commands from Role Groups

customcommands/assets/customcommands.html
This is the version I use for my fork.
It has code folding option and also working edit/delete buttons on frontpage. Line numbers are still there.
It has some forced CSS-styling with !important tags; for margins and padding - probably can be done in bootstrap. Also added back the title for delete button and span classes I had PRd before.
Probably needs to be run in YAG-testing first for feedback. Hope this concept works.
=> Suggestion: Custom Commands frontpage HTML change

common/templates/context.go, common/templates/context_funcs.go, common/templates/general.go
A new template that creates *discordgo.MessageSend from sdict , maps etc. 
Some changes to sdict conversion now using reflection.
Enable cemebed to handle *discordgo.MessageEmbed sent as argument
Changes to SendMessage function effectively enabling all existing templates ( sendMessage , sendMessageRetID etc.. ) to send Complex messages depending of datatype of argument passed being *discordgo.MessageSend.
=> Satty9361 send complex

common/templates/general.go
if there are give more or less than two arguments, it should not return 0 because 0 is valid answer for modulo. It's better to return NaN and stay in type float64 as return.
This all can also be done through errors.New().
=> update: func tmplMod

moderation/commands.go
Quickfix, currently it allows to paginate through empty pages.
=> Fix: TopWarnings pagination

customcommands/tmplextensions.go
Changing the limit from 1 to 2 as discussed.
=> Changing db_multiple limit for non-premium servers to 2

cmd/yagpdb/static/js/custom.js, customcommands/assets/customcommands-editcmd.html
Like all front-end things this is "what-if"-case. This implementation does not have a keyboard "undo" but backspace still works. "Tab" creates 8 character width and this is default.
character addition to CC total counter is added
Have run this on Safari, Edge, Chrome, Firefox, Opera, Brave.
needs testing in dev and later this class could be added to other textarea sections in HTML
=> Tab-key for custom commands

common/templates/context.go, common/templates/general.go
This should be the last addition for algebra palette.
It operates on base e, meaning natural logarithm. In mathematics, log_n is most often taken to be the natural logarithm and so does golang's math library.
if user gives second argument as base, return will be for that base.
=> templates: logarithm function

common/templates/context.go
Quite a few template like joinStr, AddReactions , exec etc accept []string as arguments but not []interface{}. Rather than doing a huge number of changes, I think conversion of Slice to []slice is a good solution. This does not allow any mutation of string slices, just an easy conversion from Slices to []string. I have implemented this using a variadic boolean flag argument which is by default false but can be set to true. If true, and any value of the Slice is not string, execution is stopped and it returns nil. Otherwise it tries to generate a sub-slice of all string values in the Slice.
=> StringSlice method to convert a Slice to []String

customcommands/bot.go
^ to \A
and $ to \z
this will always work irrespective of multi line mode being set or reset.
=> fix incorrect regex for matching.

common/templates/context.go, common/templates/general.go
Users frequently request this, although this can be done using custom commands. I really don't know why they want this or can't make their own CC, but they, the users cry about this feature constantly.
=> templates: comma separator for thousands

customcommands/assets/customcommands.html
This is the same \f106 \f107 awesome font up-down caret used in navigation panel when folding the panels. Same here.
=> HTML: caret addition to CC card

web/web.go
Currently we have two cog icons under Core - representing different things. Also fa-database represents logs in other nav section. So consistency sake let the same database icon represent logs everywhere. 
Side note, I actually \f0c5 fa-copy even better, but let fa-database be current suggestion.
=> Suggestion: replace cplogs awesome icon

premium/assets/premium.html, tickets/tickets_commands.go
It has been pointed out that finding a transcript using just the ticket number becomes difficult. Adding the ticket title in the filename would resolve this.
=> Tickets- Include ticket Title in transcripts

customcommands/web.go
Although this new icon means closed captioning, YAGPDB uses this abbreviation for custom commands and seems OK to use it here instead of just plain exclamation mark, which usually means danger : )
=> Suggestion: replacing CC awesome icon

common/templates/context.go, common/templates/context_funcs.go
This is very wished function - I dunno about rate-limits here, it is strictly told to run once per CC, that 20 emote deletions later might be a problem/can be changed to let's say 10. Runs fine on lesser test-server, needs further discussion and testing.
=> template function: delete Message Reaction(s)

common/templates/context.go, common/templates/context_funcs.go, common/templates/general.go
This function not only lets you edit both embeds and content at once but also allows for completely removing embeds by passing a nil to "embed" key in message edit builder.
=> Complex message edit

stdcommands/topservers/topservers.go
Users are searching for their server from the TOP and instead of skipping and skipping hundreds of times and making extra queries, an id flagged search is better. Had to add /common to import, because I don't know a way doing nested Selects with sqlboiler.
the query should be trimmed down from * 
I guess, because 400k+ servers is a little different than my testing : )
edit: currently 'left_at IS NULL' is also not included to query, because main command includes these servers from where YAG has left.
=> Idea: additonal ID flag for topservers command

common/templates/context.go
Users are beginning to use Unix/Discord Epoch times more and more for what I've seen, newDate template function can do it as well, but a constant dot would be handier.
=> additional constants, Epoch times

logs/plugin_bot.go
For some odd reason commands.ContextMS(parsed.Context()) does not register PresenceStatus from dstate, maybe due to member Copy - can't remember how it's called...
So this is one possible way solving it.
=> Fix: whois without arguments does not show status

automod/effects.go
mute limits should be also removed from automod v2 to be in sync with current changes.
=> Remove mute duration limits from automod v2

stdcommands/listroles/listroles.go
Has -nomana switch to exclude managed/bot roles, also a counter as response on first line.
This all can be done using custom commands, but main-command should also have it.
=> Idea to revamp listroles: nomanaged switch and counter

common/templates/general.go
users have requested location based time.Time. So it has optional string parameter having tz database syntax.
=> updated: newDate function

common/templates/context.go, common/templates/general.go
Sometimes for further analysis of characters int32 and uin8 are necessary. So these conversion functions are quick way around for that. 
PR'd them together, because these are small changes and together in code.
=> template additions: toRune, toByte

moderation/assets/moderation.html, moderation/commands.go, moderation/models.go, moderation/plugin_web.go, web/validation.go
This adds a default number of days of messages to delete while banning- which is much requested by users.
This is a better solution than #670  as it doesnt change behavior in existing servers while letting people set their own default per server. 
Should work reasonably fine from testing , however I am not 100% sure about the changes in validation.go for a general purpose, for this - it works as desired.
=> Satty9361 ban ddays config

common/templates/context.go, common/templates/general.go
This is a convenience function to convert exported field-value pairs of a struct to an sdict. It would be very handy for editing embeds and such rather than having to reconstruct the embed field by field manually. Can also be used in finding values because you can range though an sdict and not a struct and a couple other use cases. 
There are already some rather hacky ways of doing this (save to database and retrieve it) but this is better as it preserves datatypes as well as unnecessary database calls.
=> Satty9361 struct to sdict

common/templates/general.go
Helpful for consistency as fmt.Stringer works with joinStr and other inbuilt functions already.
=> Add fmt.Stringer to toString

web/template.go
Role colours are currently being wrongly displayed for those with 0's at the front of their hex values.
=> Fix role colours

customcommands/tmplextensions.go
IsSet gives `true` even if argument is not present since .Get returns `0` which is not `nil` in case carg is of type `int`. This should fix it.
=> BugFix: IsSet bug when carg is "int"

customcommands/bot.go
Add .Message as alias to .ReactionMessage in reaction commands for consistency across trigger types.
=> add .Message as alias to .ReactionMessage

common/templates/context_funcs.go
Role and everyone/here mention templates have an unnecessary space around the mentions while producing an output and this is not desirable in most situations and leads to confusion. Users can add space themselves when they want.
=> Remove the extra spacing around mentions

moderation/commands.go
Added a -to flag to the clean command.
This allows users to clean all msgs untill a certain msg by specifying its ID. 
For example: -clean 100 -to 704152928381960284
If there are only 5 msgs until the msg 704152928381960284, it will only clean 5 msgs.
=> Update to the Clean Command

common/templates/context.go
Fuction was added to general.go but not to context.go
=> Add KindOf to StandardFuncMap

verification/verification_bot.go
Clear past kick/warn scheduled events while setting up new verification process to handle bugs when users rejoin.
=> Verification (BugFix): Clear Past Scheduled Events

customcommands/tmplextensions.go
Since dicts got a few improvements, there are a few users that are storing them to DBs
Problem is that msgpack, by default, decodes maps as map[string]interface{}... So decoding dicts returns an error
This PR creates a decode that decodes maps as map[interface{}]interface{}
=> Fix decoding dicts from DBs

commands/assets/commands.html
This PR updates the note below the `ignored roles` section of command overrides. Apparently, some users were confused about the wording of "priority" here, taking it to mean that the roles were required rather than ignored, and this was a common occurrence. 
Wording before and after:
```diff
- Takes priority over required roles.
+ Users with an ignored role won't be able to use commands, even if they have a required role.
```
While this is certainly more verbose, it gets the point across clearly and leaves little room for confusion.
=> command_overrides: reword ignored roles note

moderation/commands.go
This PR adds a warning to the description of the `clean` command making it clear (excuse the pun) that the combination of `clean userId mention` is invalid. This has been a source of confusion for many in the support server who have encountered the issue, especially as the auto-generated usage implies this combination is valid, when in fact it is not.
> `Clean <User:Mention/ID> <Num:Whole number>`
It is arguable whether this is a good way to resolve the issue - should the code be changed to handle this specific combination instead? In any case, this needs to be fixed or made clear in some way, hence the PR.
Identical to #794, except target branch is actually correct this time 😄
=>  docs(clean): 'clean userId amount' is invalid

reminders/plugin_bot.go
**Summary**
Users have often requested to be able to delete their own reminders on guilds other than the guild the reminder was created in. This is usually simply an inconvenience, but can be particularly troublesome if the user has since left the guild / have been removed and cannot run the command on the proper guild.
**Changes**
* Move logic to check whether guild ID is same as reminder guild ID further down in the code
* This allows for users to delete their own reminders even if they aren't in the same server while keeping existing ability to delete others' reminders unchanged
* Improve help message for `DelReminder` to document the fact that reminders made by other users can be deleted given certain criteria are met
=> reminders: allow global deletion of own reminders

stdcommands/undelete/undelete.go
A user in the YAGPDB support server suggested this. Decided to PR it.
All this does is add a new switch to -undelete which is -u that allows you to only show a specific users deleted messages.
`-undelete -u userID/mention`
Edit: Thank you @Pedro-Pessoa and @jo3-l2 for the feedback.
=> undelete user switch

customcommands/assets/customcommands-editcmd.html
Change: `(assuming default default settings)` to `(assuming default settings)`
=> Fix errata on CC's Command trigger description

cmd/yagpdb/templates/cp_nav.html, cmd/yagpdb/templates/index.html
This effectively reverts a36976d which adds **Use Slash Commands** permission to YAGPDB.xyz's invite links.
I'm highly sure that was a mistake while preparing for Slash Commands. There is no reason bots have **Use Slash Commands** permission. Registering Slash Commands doesn't require that, instead it requires `applications.commands` on authorization that @jonas747 correctly added in c1ee6dd commit. I also don't think bots can use another bot's slash commands via API, and even they could, in most cases it doesn't make sense for bots to use them, and I don't think there is a possibility that features uses them will be added to YAGPDB.xyz.
Since the commit was only added to `master` branch and not to `dev` branch, and this pull request just reverts that, I decided to send it to `master` …
=> Remove Use Slash Commands permission from invite links

common/templates/context_funcs.go
Support for the new api endpoint to removes all reactions per emoji in form of optional args to deleteAllMessageReactions. 
Have combined with the limits for deleteMessageReaction function for the per emoji removal.
=> deleteAllMessageReactions per emoji

common/templates/context.go, common/templates/context_funcs.go
Create a function called reSplit which is basically regexp.Split
=> Give users access to regex split

moderation/assets/moderation.html, moderation/commands.go, moderation/plugin_bot.go, moderation/punishments.go
Much requested moderation unban command. Yag is used as primary moderation bot in several servers and I think its will be immensely helpful to have a formal unban command rather than using workarounds with duration and such. Also, helps in adding unban reasons for modlog for manual unbans.
Inherits same settings and permission requirements as the ban command.
=> Satty9361 unban

customcommands/tmplextensions.go
Currently, the SQL executed for `dbIncr` does not check whether the entry has expired, causing a bug where it increments the value for an entry which has already expired.
See the following code:
```
{{dbSetExpire 0 "test" 5 10}}
{{sendMessage nil (print (dbIncr 0 "test" 1) " " (dbGet 0 "test").Value)}}
{{sleep 15}}
{{sendMessage nil (print (dbGet 0 "test").Value " " (dbIncr 0 "test" 1))}}
```
This currently results in this:
As seen above, `dbIncr` increments the value of the expired entry from 6 -> 7, instead of treating it as a nonexistent entry and setting the value to 1.
This patch modifies the behavior of `dbIncr` to do this instead, treating the expired entry as nonexistent:
=> templates: dbIncr should not increment expired value

stdcommands/calc/calc.go
Temp fix for calc.go which fixes the bug found in #860 
Better solution would be to fork [this repo](https://github.com/alfredxing/calc) and fix it there, but this works for now.
=> fix bug with calc.go

customcommands/web.go
Seeing as some people still get confused when a random message along of
> Edit this to change the output of the command!
pops up, I thought maybe update it to at least state it is a custom command and what its ID is, so you can find the rogue CC easier. This is my first PR and my first time screwing around with yag's code, so *any* feedback is appreciated.
It now states
> Edit this to change the output of the custom command ##!
Where `##` is the custom command ID.
=> Update Custom Command Default Response

moderation/commands.go
When trying to report yourself, the bot answers with
```
Something went wrong when running this command, either discord or the bot may be having issues.
```
This pull request fixes that behavior by implementing a check whether the target is equal to the author. If that is the case, the bot will instead respond with 
```
You can't report yourself, silly.
```
This has been tested on a self-hosted instance and works perfectly fine. Additional feedback is, as usual, appreciated.
=> Fix report error

rolecommands/menu.go
Not a huge PR, but something that, as I think, will lift some confusion when users reset their rolemenus.
As it stands, yagpdb will not send a message when done with a rolemenu reset.
This pull request changes that, we now send a message:
```
Done resetting rolemenu!
```
Tested it on a self-hosted instance, works like a charm. As usual, feedback is appreciated!
=> Send response after done resetting rolemenu

commands/plugin_web.go
[User suggestion](https://discord.com/channels/166207328570441728/356486960417734666/822955179413995580) on the server, as Discord trims leading whitespaces why not trim whitespaces from the prefix as well.
This will eliminate such a weird prefix as an issue of the bot being unresponsive.
This change trims both leading and trailing whitespaces, however it is easy to change that to only leading whitespaces.
Up to you, but I think both is good.
If I forgot to edit something, please tell me, as far as I could see that is the only function responsible for editing the prefix. Still quite new to Go and yag's code :)
=> Trim whitespaces from prefix

common/templates/context_funcs.go
This PRs limits the `reSplit` function to 500 matches. What do you think about this limit, Jonas?
This is the number we came to a conclusion on the support server.
It also makes the `int` argument optional without breaking back comp and at the same time keeping a consistency with the other regex functions. 
This PR also makes `reFind` and `reFindAllSubmatches` accept an `int` argument, which is optional and limited to the current limit.
=> Limit reSplit and allow optional int input for reFind and reFindAllSubmatches

moderation/commands.go
Make the `clear` command check for the Manage Messages before executing the rest of the command.
From user suggestion on the server:
> Make yag display an error message when it doesn't have permission to purge messages, rather than saying it deleted a few messages when it actually didn't.
Works fine on selfhost, as far as I can see.
=> moderation: make clear cmd error if missing perms

timezonecompanion/plugin_bot.go
The old timezone thingy doesn't give you a copy paste option so it kinda sucks and people still don't know what to paste in to set their timezone. 
Old one: http://kevalbhatt.github.io/timezone-picker
New one: https://kevinnovak.github.io/Time-Zone-Picker/
=> Usage of another time zone finding service

customcommands/assets/customcommands-editcmd.html
To many people new to CC, requiring no roles/channels for CC seems like it should naturally have the same effect as ignoring no roles/channels. This is not the case -- requiring no roles/channels makes it run for nobody at all. Unfortunately, this is not something we can change without causing a breakage for people utilizing the current effect of requiring no roles/channels. A warning, however, seems appropriate considering how many people are confused by this (as seen in the help channels).
As far as I can see, it works fine on selfhost.
**Note:** There is some mild repetition in the lines added (registering the `change()` handlers) but I didn't feel like coming up with an appropriate abstraction was worth it considering it's just a few lines in total.
=> cc: add warning when requiring no channels/roles

commands/assets/commands.html
Extension to https://github.com/jonas747/yagpdb/pull/900 (I missed this in the original PR).
Issue is that the warning for trailing spaces does not show for existing prefixes with trailing spaces. In other words, if I set my prefix to `- ` and then save, the warning will disappear.
Works nicely on selfhost.
=> commands: show warning if existing prefix has space

stdcommands/undelete/undelete.go
As #907 adds a channel flag for the `log` command, it would be only fair to grant `undelete` this feature as well.
Tested it on a selfhosted instance and works fine, as far as I can tell.
=> feat(stdcommands): channel flag for undelete

common/templates/context.go
This reverts commit 0593808669143735cf2d88d014fa072e5239e71a.
There is already code in place to recover from panics during template execution (and panics in general) further up in the code hierarchy. As such, this change was unneeded and was actually counterproductive - it resulted in a variety of errors regressing from a clear error message to the rather unhelpful `paniced` error.
=> revert: recover from panics in templates

yagpdb_docker/Dockerfile
Added the ldflags from build.sh to the Dockerfile in order to add versioning and resolve the "YAGPDB Status, version unknown" status message.
Combined RUN statements to minimize the number of image layers.
Best practice according to https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
=> Dockerfile: Add versioning and reduce image layer count

logs/plugin_bot.go
Essentially like 45019a9 , just less hacky and actually handling the new presence "competing".
Little reference: https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum
Main credits go actually to mrbentarikau, I only opened the PR : )
=> Stop whois command from panicking

customcommands/assets/customcommands-editcmd.html, customcommands/assets/customcommands.html, customcommands/bot.go, customcommands/web.go
This adds the ability to run interval CCs immediately from the dashboard, as title states.
Mostly useful for testing (no need to wait for it to trigger / put it into another CC).
To prevent spam, there is a 5s cooldown -- let me know if you want this changed.
Second one looks particularly ugly but I couldn't find a better place to put it, suggestions are appreciated.
=> cc: add ability to run interval commands from dash

common/templates/context.go
Imagine if the following code just *worked*, like it intuitively should, without conversion:
```
{{$cslice := cslice 1 "hello" (sdict "a" "b")}}
{{dbSet 0 "slice" $cslice}}
{{$csliceFromDB := (dbGet 0 "slice").Value}}
{{$csliceFromDB.Append 5}}
{{(index $csliceFromDB 2).Get "a"}}
```
This PR does just that, by serializing sdicts, dicts, and cslices with a custom ext type to distinguish them from their underlying types. As far as I have seen while testing, this should never break existing code - the change is not retroactive. Furthermore, native sdicts/dicts/slices are all saved normally and are not deserialized into their equivalent custom types.
=> templates: automatically deserialize custom types

customcommands/assets/customcommands-editcmd.html
Another common mistake that's quite easy to overlook.
Works fine on selfhost.
=> cc: warning for interval triggers with no channel

stdcommands/undelete/undelete.go
User suggestion on the server and felt like adding it.
Perhaps a flag `-id` might be a better idea to maintain back.comp - lmk what you think about that
=> Display user ID in undelete command

automod_legacy/swearwords.go
Recommended to be removed by the user max-content in  #957 and #667 
"queer" is a very commonly used word in the LGBTQ+ community and is nowadays used as a non-offensive and neutral or positive self-identifier.
Leaving the word in swearwords.go for legacy automod could be seen very negatively, especially now during pride month.
While it is true that the term was used as a slur once in the past, it since has been reclaimed by the LGBTQ+ community and is generally seen as positive or non-offensive.
=> remove "queer" from swearwords.go

reddit/redditbot.go
Sometimes, when reddit users think they're funny, they use the underlying format for role and/or user mentions, which of course then mentions that role/user.
As webhooks also have an `allowed_mentions` property, setting this to empty should fix this kind of behavior - this is what this pull request aims to accomplish.
I wasn't entirely sure how webhooks behave, but I think it's better to be safe than sorry.
Couldn't test it on my selfhosted instance, as I host locally and reddit wants a legit URI for my application, different from `localhost`.
=> reddit: disallow all mentions

.github/workflows/action.yml
Due to the not infrequent PRs for `swearwords.go` against master and the like, I was so free and set up a workflow which automatically comments on such pull requests.
A pull request to `master` without changes to `swearwords.go` will mention the user to please not do that and instead change the base branch.
A pull request updating `swearwords.go` (again against `master`) will tell the user that we will **not** update legacy automoderator, however if they still wish to request critical changes, that they please change the base branch.
Both messages include a short description on how to change the base branch.
Was only able to test it on a private repository with limited capacities, but it works fine as far as I can tell.
=> Auto comments for PRs against master

automod_legacy/swearwords.go
1. Changed the sentence of first comment for a little bit, to be somewhat clearer.
1. **Removed second comment** which encourages PR or contacting for adding words. This is because of #940 and [many pull requests](https://github.com/jonas747/yagpdb/pulls?q=swearwords.go+is%3Apr+is%3Aclosed) which are involved in editing `swearwords.go` file but not merged. **This is the main point of this pull request.**
1. It seems there are some whitespaces for vertically aligning `true` boolean, but two of them are not correctly aligned when viewing `swearwords.go` file on GitHub, as well as in Visual Studio Code with monospaced font. I removed a single whitespace from each of those two to fix alignment.
=> Minor fixes for swearwords.go

common/templates/context.go
When https://github.com/jonas747/yagpdb/commit/636e5153cfdc67b10be0044d2e563236db729856 was deployed on some servers, the following code formerly used for conversion broke:
```
{{$cslice := cslice 1 "two" 3.0}}  
{{dbSet 0 "example" $cslice}}
{{$slice := (dbGet 0 "example").Value}}
{{$cslice_converted := (cslice).AppendSlice $slice}}
```
`AppendSlice` was returning an error stating that the value passed was not an array or slice.
The reason is that previously the only custom slice type that would show up is `templates.Slice`, a value type, while deserializing the cslice saved to DB results in a `*templates.Slice` - a pointer. `AppendSlice` only accepts `templates.Slice`s, not pointers, causing the issue in question.
The solution is to perform an indirection before handling the value in …
=> templates: indirect value passed to AppendSlice()

reminders/plugin_bot.go
This pull request fixes the wording of the `creminders` command. Prior to this, its help-text stated that the user needs `manage_server` permission to run this command, which is wrong - instead, it only requires `manage_channel` permission.
Furthermore, this PR also adds a new alias to said command, namely `channelreminders` - I think this is a bit more intuitive as to what the command does. Feel free to comment on that one : )
Lastly, I also fixed the wording in the `remindme` description, the word order felt a little off.
All in all, not a huge pull request.
Cheers!
=> reminders: fix wording, add new command alias

yagpdb_docker/Dockerfile, yagpdb_docker/docker-compose.dev.yml, yagpdb_docker/docker-compose.proxied.yml, yagpdb_docker/docker-compose.yml
This PR is intended to improve the current Docker support.
Dockerfile:
Added Entrypoint and modified CMD:
- The current Dockerfile does not match the syntax of docker-compose.yml and docker-compose.proxied.yml.
Those have currently no specification of the executable path and thus would fail to start a container from an image build by the current Dockerfile. 
Additional, the current CMD is written in shell format, which should be exec format instead.
Since the yagpdb_app container is only supposed to run an executable and nothing else, it would be reasonable to change the current shell format CMD to an exec format Entrypoint (/app/yagpdb) + CMD for additional commands.
Removed ENV extra_flags:
- There should be no reason to have such an ENV in the running container, since you can already …
=> Docker Improvements

stdcommands/advice/advice.go
Quite an old [suggestion](https://discord.com/channels/166207328570441728/356486960417734666/692984043389845524) which apparently was not implemented or PRd yet.
This pull request adds a little sugar to the advice command: Instead of always indexing the first item upon a successful search, we take a random item of the returned array of advice slips. Not a huge change, however I tested it as usual on a selfhosted instance and the results speak for themselves:
(sorry for compact mode - ATBDB is my selfhosted instance, LAGPDB is the officially hosted instance).
As you can clearly see, there is now more "advice" to receive, the command still functions the same. I was also so free to remove the unnecessarily redundant type declaration for the ArgDef.
Cheers : )
=> stdcommands: more answers to advice

logs/plugin_bot.go
`Whois` was dereferencing `member.Member` without checking if it was nil first, thus, in some cases where the `Member` fields is not present in the `dstate.MemberState` object, the bot would panic.
=> Fix potential panic from whois

commands/tmplexec.go
Handle `discordgo.User` types in exec.
Typically the type is `*discordgo.User` but the value type can pop up in some places. In particular, the `User` field on DB entries is a `discordgo.User`, not a `*discordgo.User`.
Thus, the following code:
```
{{dbSet .User.ID "test" 0}}
{{$u := (dbGet .User.ID "test").User}}
{{exec "warn" $u "test"}}
```
...would error out with `Unknown type in exec, only strings, numbers, users and string slices are supported`.
=> commands: handle user value type in exec

common/templates/context_funcs.go
Some QoL improvements to setRoles to make it nicer to use based on user feedback.
1. Deduplicate input slice of roles, this makes it easier to write code that adds multiple roles to users in a single go. Let's say a user had 249 roles, and we want to add 5 roles to them. If we just add those 5 roles to their member's role slice, it's going to error currently. It would be nice if we filtered out duplicates in the input slice so it "just worked".
2. Add in managed roles automatically. You can't remove managed roles, so currently users have to take into account managed roles and add them to the input slice manually. We can do that for them instead.
3. Support `nil` for member parameter (uses the context member).
4. Support role structs as input, this is just something nice to have.
=> templates: qol improvements to setRoles

logs/logs.go
This was also a fairly old [suggestion](https://discord.com/channels/166207328570441728/356486960417734666/754098618620706906) on the support server:
> For logging with the `-logs` command, specifically logging embeds, use the JSON version of the embed so that there is at least some form of embed logging, rather than "(x embeds is not shown)".
This pull request adds this kind of behavior, although I was not able to indent it beautifully for some reason. 
Let me know what needs to be changed for it to do that, or if this is intentional.
I decided to take this action on all embeds of each message, if they exist. Feedback regarding this is appreciated, as well.
As usual, I tested this on an selfhosted instance and as far as I can tell, it works fine:
Cheers!
=> logs: show underlying JSON of embeds

streaming/assets/streaming.html, streaming/bot.go
Fairly trivial, bots shouldn't get the role as this feature is technically meant only for members - No sane person would seriously want to have the "streams" of a bot announced, as those bots do it mostly for cosmetic reasons. (Purple is a nice color!!)
This pull request extends the check for the presence by a check whether the member in question is not a bot - if so, continue and grant the role.
Let me know when I missed something.
=> streaming: ignore other bots

cmd/yagpdb/templates/cp_main.html, moderation/assets/moderation.html
As not few people are regularly confused over the admittedly strange syntax in the helper texts for the template fields found underneath
* Moderation DM fields
* Join / Leave Feed/DM
will this PR aim to make the phrasing clearer by simply showing the object and linking directly to the template reference of said object: (example taken from the moderation page):
> `{{.User}}`: `.User` object documentation - the user being muted
As usual, should I've forgotten an edit, please do not hesitate to mention that. I've tested my changes on an selfhosted instance and as far as I can tell, everything works just as fine as it did before.
---
Related issue:
=> web: Reword helper texts to link to documentation instead

yagpdb_docker/Dockerfile, yagpdb_docker/app.example.env
Dockerfile:
- Revert the move of copy operations to builder from the last Docker Improvements PR  #982, and instead run them in the final image again to make use of image layer download caching. 
Having separate image layers for static/ and templates/ in the final image allows us to cache these when pulling new images from Dockerhub. This means we only need to re-download the image layer with the binary and don't need to re-download the image layers for static/ and templates/ if they weren't changed.
This reduces the total download traffic when pulling new images, due to static being close to the size of the binary itself.
- However, we leave the copy-templates operation in the builder so we only have one image layer for all templates.
- And we remove yagpdb/cmd/yagpdb/posts due to it …
=> Docker Improvements again

premium/patreonpremiumsource/patreonpremiumsource.go
This PR aims to fix an issue wherein pledging for more premium slots than what's available from the existing plan, causes the slot title to increment in an unintended way, i.e - start the count from `0+len(userSlots)` instead of `1+len(userSlots)`.
The underlying image shows a scenario where 4 additional slots were pledged for, resulting in the count of additional slots to begin from 1 instead of 2:
This change fixes it, by simply adding a 1 to the calculated value.
=> premium: fix slot count in titles

common/templates/structs.go
Long story, but essentially:
```
{{ $x := getChannel 0 }}
{{/* x is a nil pointer of type *templates.CtxChannel */}}
{{ $x.Mention }}
{{/* Rather than erroring, the template library calls Mention() on the nil pointer (??) and causes a panic when c.ID is accessed */}}
```
Technically speaking this is sorta-ish a bug on the template library side - see https://github.com/golang/go/issues/28242, which has essentially the same repro. There, they decided to keep this behavior (calling methods with nil receivers) because it's a valid thing to do in Golang. However, they did make a change - better error messages to make it clear what the issue was; the commit was included in the batch update PR I sent to the template repo (https://github.com/jonas747/template/pull/2) but isn't deployed.
Anyhow, I …
=> templates: fix <channel>.Mention() method when called on nil ptr

rolecommands/bot.go
This was a user suggestion on the server. Seeing as the `create` subcommand also has an alias `c`, it's only fair to also give an alias to `remove`, namely `rm`.
Thanks in advance : )
=> rolemenu: add alias to `remove` subcommand

moderation/commands.go
Because Discord only allows for a max reason length of 512 characters, we limit the reason to 470 characters, as we prepend it with the username and discriminator as well as two formatting characters.
As it stands, YAGPDB just responds with 
> Something went wrong when running this command, either discord or the bot may be having issues.
This pull request adds a check and responds with
> Error: Reason too long (can be max 470 characters).
Should the reason's length cause it to exceed max character count.
Relevant [suggestion](https://discord.com/channels/166207328570441728/356486960417734666/844968308360216646) on the support server.
=> moderation: Limit ban and kick reason length

stdcommands/wouldyourather/wouldyourather.go
As title states, making this command a bit more consistent with a few other fun-category commands, such as `xkcd`, or `hltb`.
Works, as far as I can tell, fine on selfhost.
Code originally made by mrbentarikau, I'm just the delivery boy  ; )
=> stdcommands: Embed response of wouldyourather

customcommands/bot.go
There is a visual bug with the `cc` command that, when initially set a text trigger and then a changed trigger type not based on text, this text-trigger will still be shown:
This pull request aims to fix that issue.
Bug pointed out by `bonbom_#6542` on the support server.
[relevant bug report](https://discord.com/channels/166207328570441728/214439334089195521/846072305482203167)
=> fix(cc): visual bug with trigger text

common/templates/context.go
This was a suggestion on the support server, exposing the inbuilt functions `HasPrefix` and `HasSuffix` from the Go `strings` library.
As far as I can tell, it works fine on selfhost - this is the first time that I added things to the scripting language, so any advice / tips are highly appreciated.
=> templates: Expose `HasPrefix` and `HasSuffix` from the Go library

discordlogger/discordlogger.go
Guild names can be server invites, which allows people to promote their servers in the join-logs. This PR fixes just that, by replacing server invites with the text `[removed-server-invite]`, as seen in the image below:
=> discordlogger: remove discord invites from guild names

premium/assets/premium.html
Since other payment methods are no longer accepted, this PR removes
- the alternate methods that were accepted earlier. 
- the pricing information which can directly be seen on the Patreon page along with the benefits they offer, in a much better fashion.
=> premium: remove old payment methods from the dashboard

common/templates/context.go, common/templates/context_funcs.go, customcommands/bot.go, customcommands/tmplextensions.go, notifications/plugin_bot.go
Like #919, but with a clean history.
This pull requests adds several needed fixes to the DM templates in YAGPDB's custom command scripting.
We simply check if the template is being executed by the leave message, if that is true, it will fail to send the message.
This is to remedy the "abuse" of `execCC` to still be able to send a leave DM, and should be quite future-proof.
Moreover, we add the info text we can see in `sendDM` to the other DM template `sendTemplateDM` - Luckily @Pedro-Pessoa helped me with that, so a big kudos to him.
Of course, this might be a small-ish breaking change (again), but I think it is more important to block leave DMs entirely.
Everything works, as far as I can tell, fine on a selfhosted instance.
Cheers!
=> totally disable sending DM on leave message

stdcommands/wouldyourather/wouldyourather.go
Misses a newline and had one asterisk `*` too much. This PR fixes that.
=> wyr: hotfix formatting

common/templates/context.go
Hi!
This commit https://github.com/botlabs-gg/yagpdb/commit/78dee86a0958565066fe1337b7794d2d758ea10a tried to prevent users being able to send DMs without it showing where it was from. 
It pretty much solved the issue, but there is still a way of doing it. This PR aims to fix this.
=> fix not showing dm info

stdcommands/roll/roll.go
As title states -- sometimes users use uppercase letters for their RPG-format and receiving an error over case sensitivity is not a good experience.
The screenshot showcases the behaviour:
=> stdcommands/roll: make command case insensitive

frontend/static/js/spongebob.js
Use bigints for channel permissions, as discussed on Discord. This fixes the issue where the control panel claims that YAGPDB's missing some permissions despite it actually having said permissions.
Tested on a few control panel pages with various bot permissions on selfhost, and it appears to work fine.
=> web: use bigints for channel permissions

customcommands/bot.go
Concurrect is not a word.
Concurrent is. And used in several other comments, and should be searchable.
=> Spelling correction in comment.

customcommands/bot.go
This PR adds the CCID to the error message when rune count is bigger than 2k
=> ccs: add CCID to rune count error response

stdcommands/wouldyourather/wouldyourather.go
There was/is a small typo in the would-you-rather prompt, namely one colon too much.
Also using this opportunity to increase the favicon size used for the author icon, as it is a little blurry standing now.
=> stdcommands: fix a typo in wyr and increase favicon size

.gitattributes, README.md
This pull request reworks the README and adds git attributes.
The README was quite outdated and fairly cluttered. This rewrite aims to make it easier to navigate and read. Important sections with the intention to "sell" this bot have been moved to the top to make them easier spot. Markdown syntax has been updated to be more consistent throughout the file, so that reading the raw document is becoming easier as well.
Some sections have been removed, as they are no longer true or necessary. Additionally, the step for building has been changed from `go build` to instead run the `build.sh` script to make an actually deployed version of the bot -- this has been mentioned several times to new users in `#self-hosting-discussion` on the server, so including that in the README is quite fair.
Git …
=> Repo: Rework README and create gitattributes

.gitattributes, README.md, common/templates/context.go, customcommands/bot.go, frontend/templates/cp_selectserver.html, frontend/templates/index.html, go.mod, go.sum, moderation/commands.go, premium/assets/premium.html, stdcommands/define/define.go, stdcommands/poll/poll.go, stdcommands/wouldyourather/wouldyourather.go
Being a command that isn't used very often, it seems to a common problem where users cannot remember what the command is called. This PR adds two aliases, a little more intuitive and easy to remember.
=> moderation: add "delwarn" and "deletewarning" alias to the delwarning command

logs/logs.go
Since yag has been able to see threads, it also happens that logs were created in threads.
For the time being, this always threw an error; this pull request fixes that regression.
Attached you'll see me in a thread together with my selfhosted instance. First, the error the user sees and the error that's been logged is shown, then the fix.
=> logs: Fix unable logging threads

moderation/commands.go
Discord allows unix timestamp formatting which makes it a lot easier to see the time in the local timezone. This PR makes changes to allow the `warnings/warns` command to use discord's timestamp formatting instead of the current UTC timestamp string.
=> moderation: use discord unix timestamp in warnings

reminders/plugin_bot.go
Seeing as Discord shipped a feature that allows users to format Unix timestamps which also handles localization, this is more or less an accessibility feature. Some users may not know what UTC is or not know how to convert from UTC to their local timezone, we can let Discord (or rather, the user's OS) handle conversion for them.
The format used is a shorthand format with the following setup:
```
d Month yyyy hh:mm
```
=> reminders: use Discord timestamp formatting

stdcommands/undelete/undelete.go
[This commit](https://github.com/botlabs-gg/yagpdb/commit/afe4ff86a5d02e74843536ff27c415eb1cc84187#diff-28f1ccb8bb89d126cce366fb047ce349b4631803dfeeb38c98775de285c429a2) introduced a presumably accidental change to `undelete`, which caused the command to only show the messages recently deleted in the channel of execution, despite the `-channel` flag being used.
This PR aims to fix that regression. I've tested it on a selfhost and everything works fine (again), as far as I can tell.
=> stdcommands/undelete: fix channel messages not being fetched correctly

verification/verification_bot.go
Presently the verification module indiscriminately warns/kicks users unless they were verified directly through YAGPDB. There have been several suggestions to have it recognize if the user is given the verified role manually (in case the user cannot verify directly); this change implements that.
Thank you to @mrbentarikau for adding this code on his selfhost so I could test it. Seems to work fine, as far as I can tell.
=> verification: don't kick manually verified members

moderation/commands.go
There have been occasions where users were wondering how many warnings have been given on the server, either due to curiosity or simply wanting to have a metric of some sorts.
=> moderation: show server warning count

common/templates/context_funcs.go
This fixes message-reaction functions for templating system if they get nil arguments either as messageID or userID... causing *reflect: call of reflect.Value.Interface on zero Value* soft-panic.
=> FIX: templates > add/delete MessageReactions having nil arguments

rolecommands/menu.go
Prior to this, the error was displayed as an "unknown error",
causing quite confusing situations for users, as most are not aware
of the 20 reactions-per-message limit.
Now, users will be made aware of said limit with a more descriptive
error message.
=> rolecommands/menu: tell error on too many reactions

commands/assets/commands.html
Users often get confused and think flags also change along with the prefix. This PR adds a note talking about this, and also uses `rolemenu create` instead of `ping` in the example, to show the usage of flags with the user's set prefix.
=> commands: add a note explaining the effects of prefix change on flags

customcommands/assets/customcommands-editcmd.html
- Use a monospace font for the web CC editor.
- Fix the character counter on the frontend not matching the backend by double-counting newlines.
=> cc: improve web cc editor

common/templates/context.go
Add `Dict.HasKey` and `SDict.HasKey`, for checking whether the dictionary contains an entry for a particular key.
Presently, the status quo for checking whether a dictionary contains some key is to look up the entry and see if the value is truthy:
```
{{ if $d.Get $k }}
{{/* $d has an entry for $k */}}
{{ end }}
```
The `HasKey` method improves on this in two ways:
1) It makes the code more self-documenting -- `$d.HasKey $k` is clear in intent.
2) It is more correct in edge cases -- if the dictionary can contain entries with zero values (e.g. 0, false) then `if $d.Get $k` may erroneously report that $d has no entry for $k.
=> templates: add [S]Dict.HasKey method

common/templates/context.go, common/templates/context_funcs.go
This adds the template `getPinCount channel` which returns the total number of pins in a channel. The command is limited to 2 calls per CC for non-premium and 4 calls per CC for premium because it has to get all pinned messages in the channel to be able to find number of pins.
=> common/templates: add getPinCount template

common/templates/context.go, common/templates/general.go
This is cbrt (cube root) function from golang's math library. It's more convenient and even more presice to use than {{ pow $x (fdiv 1 3) }}
=> templates: Cube Root function

common/templates/context.go, common/templates/context_funcs.go
Being able to pin/unpin messages with the bot has been a common request. This PR does just that by adding custom command templates which allow pinning/unpinning a message.
The syntax for the template usage will be:
- `pinMessage channel messageID`
- `unpinMessage channel messageID`
=> common/templates: add templates to pin and unpin messages

common/templates/context.go
Users have mentioned the need of trimming white space around string many times, will add the simplest of trims golang strings package offers > all leading and trailing white space as defined by Unicode removed, 
Also starting a trend to alphabetically order StandardFuncmap keys already in the code, but this is not the purpose of this PR.
=> templates: trimSpace function

common/templates/context.go, frontend/static/js/custom.js
This pull request will cause the `Tab` key to add indentation instead of jumping to the next element when in one of the textareas.
=> Update custom.js to make indentation easier

common/templates/general.go
Remove a counterproductive check for the settability of fields in `structToSdict`. This fixes a bug where calling `structToSdict` on a struct of a value type (as opposed to a pointer) resulted in an empty map:
```
{{ $x := index .Guild.Channels 0 }} {{ structToSdict $x }}
{{/* empty map; $x is of type dstate.ChannelState */}}
{{ $y := .Guild.GetChannel .Channel.ID }} {{ structToSdict $y }}
{{/* filled map; $y is of type *dstate.ChannelState */}}
```
After this patch, both produce similar output, as desired.
For context, `reflect.Value.CanSet` reports whether the corresponding field can be written to. Since we are not writing to the fields of the struct -- we're just reading the values -- the check is unnecessary. Further, since only reflection values obtained from a value containing a …
=> templates: unconditionally include fields in structToSdict

customcommands/bot.go
Another thing users have requested is to query for the trigger's "name"... especially useful when dealing with regex. So it will add another context data element {{ .CCTrigger }}.
=> context data: CCTrigger

commands/help.go, stdcommands/throw/throwthings.go
This is a command that is used quite often, and people can get confused with the "bot blocked" part in the error, as simple having your direct messages closed also prompts the same error. Just adding the "DMs closed" to the error could make things better
=> Update help error message

customcommands/tmplextensions.go
Any execCC calls currently break the command they're used in if said command is executed in a thread. This should hopefully fix that!
=> FIX: customcommands: fix execCC in threads

common/templates/general.go
This fixes the error `reflect: call of reflect.Value.Type on zero Value` resulting in small recoverable ExecPanic by YAGPDB if second given argument for template function `in` is of zero value.
=> FIX: templates: in function

common/templates/general.go
User suggestion on the server, to allow for more flexibility when outputting files as custom command response.
* We add a new key to `complexMessage`; `"filename"` - its value will be the file's new name instead of `Attachment`.
* Because this new key is optional, we will default to `Attachment`, if no filename given.
* The custom filename will be limited to 64 characters, this seems like a reasonable limit.
* The file's extension will be hard-coded to `*.txt` as countermeasures against abuse of `*.bat`, `*.wav` or other wonky fonky file formats.
I decided on no-op when a filename but no file is given. Just doesn't make sense to give a filename without a file, and when it does happen it seemed to much to stop the CC execution over something that has no effect whatsoever.
As far as I can …
=> common/templates: allow file renaming

common/templates/general.go
Follow-up to #1122.
The original check, `CanSet`, was too narrow (as explained in the prior PR), excluding fields on struct value types. However, removing the check entirely resulted in a regression; `structToSdict` would attempt to include unexported fields which resulting in panics.
This patch adds back a different check, `CanInterface`, which only excludes unexported fields. This avoids panics (`CanInterface` is true iff `Interface` does not panic) while still fixing the issue mentioned in #1122.
Thank you to @mrbentarikau for alerting me to this issue and to @buthed010203 for discovering it.
@ashishjh-bst, this fixes a regression introduced by a previous PR that has not yet been deployed (and so it's important to either revert the previous PR or merge this one before the next deploy.)
=> templates: add CanInterface check to structToSdict

customcommands/customcommands.go
This PR makes the changes requested [here](https://trello.com/c/nEj73iGd) and changes "hour" to "hourly".
=> customcommands: fix typo in hourly interval error

commands/assets/commands.html, commands/plugin_web.go
**YAGPDB Control Panel > Core > Command Settings**
User was able to add and save negative and very large values for "Autodelete Trigger after" and "Autodelete Response after".
This pull request adds range validation for these fields in both Channel and Command Override.
=> Added validations for Autodelete trigger and response deletion delay

frontend/static/css/custom.css, frontend/static/vendorr/bootstrap-multiselect/bootstrap-multiselect.js, frontend/templates/cp_main.html
For every multiselect on the YAGPDB web app, there was bootstrap's dropup being used. In some cases when the options are less than three, there was a visible gap between the dropdown toggle button and the options list as can be seen in the following screenshot:
This PR fixes the issue by removing the extra 125px from top.
Also changing the dropup to dropdown to make the single select and multiselect consistent.
The new is shown in the following screenshot:
=> Fix gap between dropdown toggle button and options list

web/template.go
When roles selected in "Automod v2 conditions" are deleted, the menu shows "Deleted Role: 0" for each deleted role. When you try to uncheck all these roles and proceed to save, only one of the roles is removed at a time from the list.
The root cause of the issue was that all the deleted roles were assigned value="0" in the <option> tag. Due to this, the multiselector was behaving abnormally. This PR updates the value of such roles with their ID (which will be unique).
=> Fix deleted roles not getting removed simultaneously from automod-v2 drop down

moderation/commands.go
The user argument was not required in -warns or -warnings command, so it was taking 0 as default user id. This PR makes the user argument required for this command to run.
=> Make user argument required in warnings list command

autorole/autorole.go, moderation/models.go, reddit/plugin_web.go, reputation/plugin_web.go, rolecommands/web.go, verification/verification_web.go, web/validation.go
1. Updated the readMinMax function to handle empty max value so that only min value can be provided (for example: a field that requires positive number, hence min=0 and no max value). For this field the validation will be described as:
```
type Example struct {
PositiveField int `valid:"0,"`
}
```
Here only min value (0) will be validated, and if negative value is entered, it will show an error:
```
Positive Field: should be at least 0
```
2. Several forms on the control panel didn't have proper validations on the backend, this PR adds those validations.
=> Update middleware validator to handle only min value, add min value validations in various forms

customcommands/assets/customcommands-editcmd.html, customcommands/web.go
On Edit Custom Command page, if the type of command is interval based, then a button Run Now is shown along with Save and Delete buttons. The button when clicked just ran the custom command without updating it (if there were any changes).
This PR adds an API `/manage/{{$guild}}/customcommands/commands/{{.CC.LocalID}}/update_and_run` which is triggered from that button, and updates and then runs the custom command.
=> Add API to handle update and run now for interval custom commands

customcommands/interval_test.go
Some test cases were failing after the condition for validating `TimeTriggerInterval` was added. This PR updates the interval in those settings to be in the new range.
=> Update TimeTriggerInterval to 5 in interval test cases

autorole/assets/autorole.html
At one time, user can set either the duration for autorole, or the flag `OnlyOnJoin`. This PR disables the autorole duration field when the OnlyOnJoin flag is enabled, and vice versa.
=> Disable autorole duration input field if the OnlyOnJoin flag is enabled

customcommands/tmplextensions.go
This was brought up on the support server, where a user tried to give a
thread as channel argument using `parseArgs` in their custom command.
Arguably, the current behaviour can be considered intended, however I
personally believe that adding another (if not two more) variations like
`"thread"` and `"channel-or-thread"` are undesirable and add more
complication than necessary.
The normal user would expect `parseArgs` to accept also threads as a
`"channel"` carg, and this commit implements exactly that behaviour.
=> templates: support threads in `"channel"` carg

go.mod, go.sum, stdcommands/calc/calc.go
One dependency is changed: from alfredxing/calc to ei14/calc.
Compared to alfredxing/calc, ei14/calc is different by 1 line.
Prior to this fix, `-c acot(0)` returns 90 despite the fact that every other trig function is in radians. Furthermore, `-c acot(1e100)` returns 90 - pi/2 instead of a near-zero value as it should. These discrepancies are caused by `acot` being calculated as `90 - atan` instead of `pi/2 - atan`.
ei14/calc has a correct implementation of `acot`.
=> Fix calc dependency to include a correct implementation of acot

customcommands/bot.go
This commit modifies `customcommands/bot.go` to use the `CSOrThread()`
method introduced with support for threads.
Previously, reaction-based custom commands were not triggering inside
threads, as the `EventData.CS()` method only works for true channels,
unlike `EventData.CSOrThread()`, which also supports threads.
This regression was most likely an oversight when introducing thread
support in YAGPDB.
=> customcommands: use CSOrThread() instead

common/templates/general.go
A rather cryptic error pops up when you run `randInt a b` where `a >= b`: `invalid argument to Int63n`. Improve it a bit so that the error is easier to understand without needing to look through Go docs for what `Int63n` is.
=> templates: improve randInt error when start >= stop

automod/rulepart.go, automod/triggers.go
This adds 2 new triggers to amodv2:
1. Message with more than x characters
2. Message with less than x characters
Character count is done via `utf8.RuneCountInString`
=> amodv2: create Message Length Trigger

autorole/assets/autorole.html, autorole/autorole.go, autorole/bot.go, autorole/plugin_botrest.go, autorole/web.go
This PR includes following changes:
1. Disable Autorole config form while the full scan is running.
2. Iterate through members to find members eligible for autorole, and keep them in a sorted set.
3. After all the members are iterated, launch a go routine to assign role to the members in the given set.
4. Add button to allow cancelling the full scan while it is running.
5. Add full scan status along with number of members to which the role was assigned on the Autorole config dashboard.
=> Improve autorole assignment through Retroactive Full Scan

autorole/assets/autorole.html, autorole/autorole.go, autorole/bot.go, autorole/plugin_botrest.go, autorole/web.go
1. Check from guild chunk nonce before starting the full scan iteration.
2. Handle cancel event using redis.
3. Remove unused lines from Autorole config webpage, highlight assigned members count.
=> Handle unknown guild chunk events and cancel through redis for autorole full scan

README.md, autorole/assets/autorole.html, breaking_changes.md
1. Add redis minimum required version as 5.x in README.md
2. Update breaking_changes.md
3. Update autorole full scan description on the configuration page.
=> Update redis requirements in readme, update autorole full scan text description, update breaking_changes

common/util.go
The current implementation of link validation is, although technically
correct, too sensitive; e.g. it considers an ellipsis (`...`) a valid
link.
This commit modifies the link validator regexp to only consider URLs
with a leading protocol. This should cut down on the reported
false-positives.
The change is justified by the fact that URLs with no leading protocol
aren't "clickable" in Discord either, and as such having it optional is
an anti-pattern, despite the technically correct implemementation.
=> common/util: remove optional protocol from link regex

automod/effects.go, automod_legacy/bot.go, moderation/commands.go, moderation/punishments.go
This PR makes the following changes:
- change the `KickUser` func to accept number of messages to delete, as a parameter.
- change occurrences of the func to incorporate the new parameter.
- add a `cl` flag to the `kick` command to specify number of messages to delete (1-100).
=> add a flag to delete optional amount of messages on kick

common/templates/context.go
Add in-built regex-constants for parsing links and domains from common/util.go to Custom Commands. It gives a quick solution to detect links like automoderators do.
How to name these needs a discourse. Also c.Data fields in alphabetical order.
=> DomainRegex and LinkRegex to Context Data Dot

CONTRIBUTING.md
This PR updates CONTRIBUTING.md to ask suggestions to be made on the support server instead of issues on the repository.
=> redirect to support server instead of repository issues to make suggestions

cmd/yagpdb/sampleenvfile, stdcommands/owldictionary/owldictionary.go, stdcommands/stdcommands.go, yagpdb_docker/app.example.env
> **Warning:** Though I believe a dictionary is a useful tool to have as a built-in command, there are undeniably some occasional slight issues with the output of this command due to the API used, so feel free to decline this if you feel it isn't worth it.
This adds an English dictionary command using the [Owlbot API](https://owlbot.info/). I've been testing it for a few days now and while it has some quirks it produces good output in a majority of cases. However, sometimes it does produce improper output -- for example:
I will say though that out of the dozens of words I have tried with it that's the very worst that has happened, typically it produces reasonable definitions, as an example:
It does require an API key to use, but there are no limitations or bullshit required to sign up …
=> stdcommands: add an english dictionary lookup command

commands/tmplexec.go
`userArg` uses the same internal API as `getMember`, so there's no reason for it to have a separate call counter.
=> commands: use API call counter for userArg

common/templates/context_funcs.go
Currently, calling `Link` on the Message struct returned from `getMessage` in a custom command results in an invalid link where the guild ID is 0. Interesting enough, the issue is not on our end -- Discord simply does not return the guild ID when calling the get message endpoint.
Ideally, we would patch the resulting struct in the `ChannelMessage` call itself, but that would mean that all callers would have to pass in an additional guild ID, even if they don't really need the returned structure to have one. Thus, given that the sole use of `message.Link` is in the context of custom commands, this PR opts to patch the result in the `getMessage` function directly.
=> templates: patch getMessage result to incl guild ID

common/templates/context.go, common/templates/context_funcs.go
`IncreaseCheckStateLock` is a relic of the older state tracker, which required locking the state before, e.g., iterating through roles, in order to avoid data races. The new state tracker introduced about a year ago does not impose this requirement, so `IncreaseCheckStateLock` is no longer necessary. This PR removes it and switches existing references to different call counters.
=> templates: remove IncreaseCheckStateLock

customcommands/assets/customcommands-editcmd.html, customcommands/web.go
-  For command triggers, display the prefix to the left of the actual trigger. The prefix will be hidden for all other trigger types. Inspiration for this change comes from a fairly popular suggestion (18 upvotes, 1 downvote) on the server from a while back.
- Show the last run time and the trigger length.
- Add <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd> as a shortcut to save the command.
Before:
After:
=> customcommands: improve editor ui

lib/discordgo/restapi.go, lib/discordgo/types.go, moderation/commands.go
By default, the mute role removes the permission to speak in VCs from the member. However, if a member is in VC at the time at which they are muted, they will still be able to speak. To prevent this, many other moderation bots disconnect the target member from VC upon mute, something that has been suggested for YAGPDB as well.
This PR implements support for disconnecting members from voice in package `discordgo` (code loosely based on an old PR from Satty; see https://github.com/botlabs-gg/discordgo/pull/10) and then uses it to implement the desired change in the mute command.
=> moderation: disconnect member from VC upon mute

common/templates/context.go
Make `regexp.QuoteMeta` accessible in templates.
Often users want to embed strings into regexps to be matched literally (i.e. a server prefix), currently they have to do one of two things: use `\Q...\E`, or escape all metacharacters using `reReplace`. Both are easy to get wrong: it's easy to overlook an important detail when using the former approach or forget a metacharacter when using the latter.
=> templates: add reQuoteMeta func to escape metachars

commands/util.go, lib/dcmd/arg.go, lib/dcmd/arg_test.go, lib/dcmd/cmd.go, lib/dcmd/parse.go, moderation/commands.go, reputation/plugin_bot.go
Presently, `-clean user_id n` (e.g., `-clean 204255221017214977 1`) fails with 
> Invalid arguments provided: Num is too big (has to be within 1 - 100)
The issue is that the user ID argument is erroneously interpreted as the number of arguments to be deleted. That is, the argument combo with the user argument first and the number second is selected, while it should be the other way around.
This PR fixes the issue with the `clean` command and additionally supercedes #1196 through using argument combos in a way that was not previously possible.
The underlying cause of the issue is that the integer argument type does not take its range into account when matching (the float argument type has a similar issue.) In other words, given an integer type bounded to the range `[1, 10]`, the value `11` …
=> dcmd: refactor combo selection algorithm

customcommands/assets/customcommands.html, customcommands/web.go
This PR adds a text message before the `Create a new Custom Command` button to show how many commands are created, and disables the button if the limit is exhausted.
See the screenshots below:
=> Add count and limit on CC control panel, prevent creating new CC if limit is exhausted

logs/assets/logs_control_panel.html, logs/web.go
1. The dropdown to handle roles for logs access will be removed if access for everyone is selected.
2. Allow only selected members or owner/admins/members with manage server permission to view logs.
=> Show logs only to selected roles or remove the roles selector if everyone is selected

commands/help.go, commands/yagcommmand.go, moderation/commands.go
Document user permission requirements for commands in the `help` response.
Defaults to using a new optional field on `YAGCommand` and falls back to generating a message based on the `RequireDiscordPerms` field.
=> commands: add user required perms to help embed

reminders/plugin_bot.go
Allow users to set the channel in which their reminder is sent, provided they have read and send message permission in said channel.
This was a user suggestion on the server, also fixes #953.
Works fine on selfhost.
=> reminders: add -channel flag to set reminder channel

common/templates/context.go, common/templates/general.go
Adds user requested golang math package's max/min functions as template functions. Working logic is similar to tmplPow
=> templates: max min functions

stdcommands/wouldyourather/wouldyourather.go
The author icon in the `wouldyourather` command is a low-quality icon of YAG's avatar, which doesn't look right. Since it doesn't make much sense to display the avatar in the embed anyway, since users can already see who the message is from, removing it altogether seems like a better option than using an image/icon with a better resolution. To balance the changes out in the author icon, the footer icon with the user avatar is also removed in this PR.
Current Embed:
Embed after the changes:
=> stdcommands/wouldyourather: remove author and footer icon from embed

customcommands/assets/customcommands.html
This PR makes it clearer UI-wise what action triggers the trigger for reactions.
"reaction added + removed" needs discussion, maybe "or" is better. Although CC-edit view uses plus.
=> custom commands main view reactions clearer

common/templates/general.go
This prevents unnecessary reflect errors from happening when argument type is not of time.Duration...
=> CC: humanizeDuration functions parameter as type interface{}

automod/db_schema.go
removed CREATE INDEX from automod_violations rule_id as deleting a rule has a cascade effect on update automod_violations rule_id column and causes CPU spike on db.
=> Removed `CREATE INDEX` statement from automod_violations rule_id 

common/templates/context.go, common/templates/context_funcs.go, common/templates/general.go
Often users want to check permissions in CC (i.e. they only want admins to run this command, but don't want to specify a role). Currently the main way of doing this is using `-viewperms` and then using string manipulation to check the permissions. This is 1) possibly unsafe, if the user does not strip the username from the resulting text, 2) easy to get wrong. Furthermore it's basically a waste of an `exec` call just to get user permissions.
This PR adds the following:
* Constants for Discord permission bits on the dot.
* `bitwise*` funcs to manipulate permissions.
* `hasPermissions/targetHasPermissions/getTargetPermissionsInChannel` funcs to get Discord permissions of users. (should `Permissions` be singular or plural here? dunno...)
Works fine on selfhost, as far as I can tell.
=> templates: add permission checking funcs + bitwise ops

moderation/commands.go
As described by the title, this PR makes the report command's response ephemeral.
=> moderation/commands: make report command's response ephemeral

rolecommands/menu.go
It was suggested in the help channel that some wording be added to the reply from YAG when a rolemenu had not been completed. This PR adds that text.
=> "Rolemenu complete" text to YAG responses.

customcommands/bot.go
This commit updates the `customcommands` command to handle responses
over 2000 characters in the way to instead send them to a file.
This was a suggestion on the support server, the relevant link follows:
https://discord.com/channels/166207328570441728/356486960417734666/927246757501480990
I've tested my changes for single responses over and under 2000
characters, as well as multiple responses, over and under 2000 together
respectively.
=> customcommands: handle responses over 2000 chars

commands/plugin_bot.go
The function `ensureEmbedLimits` probably used outdated
information for enforcing embed limitations put in place.
This commit limits fields to 1024 characters in size, as that is the
current limit.
=> commands: impose proper limits on embed fields

reputation/plugin_bot.go
The `user` switch I added for the `toprep` command in #932 was broken in that it always displayed the first page (as the SQL query returned `1` regardless of the actual position of the user.) This PR changes the SQL query to actually return the position of the user and also fixes an off-by-one in the calculation of the page number.
Thanks to Mr. T for alerting me to this issue.
=> reputation: fix broken toprep user switch

bot/paginatedmessages/paginatedinteractions.go
Discord mobile on android seems to display the current next and previous buttons in an odd fashion wherein one looks different from the other. 
- Discord on PC
- Discord on Android
This PR changes the emojis used for next and previous buttons to avoid such a problem.
- Discord on Android after changes
=> bot/paginatedinteraction: change next and prev emoji arrows to remove discrepancy

logs/plugin_bot.go
This PR removes the usage of the function, `discordgo.EndpointUserAvatar()` and replaces it with `user.AvatarURL()` in the `whois` command to deal correctly with animated avatars and return a GIF instead of a PNG, effectively changing the displayed thumbnail and a field.
=> logs/plugin_bot: fix whois to work with animated avatars

automod/assets/automod.html, automod/effects.go
Added a channel dropdown to allow Send Message effect to send the message in separate channel if required.
=> Allow Send message effect to send message in different channel

automod_legacy/rules.go, automod_legacy/rules_test.go
This PR aims to rewrite the logic of the cached invites in the automod_legacy package.
The old logic was messy, I find this new one much cleaner.
Other than that, this logic is orders of magnitude faster.
---- Edit
Removed the benchmarks because of the discussion in the community server, see here: https://discord.com/channels/166207328570441728/920615133993107467/1004781523557429349
=> amod_legacy: rewrite cached invites logic

common/templates/context.go, common/templates/context_funcs.go, common/templates/general.go
Added key `reply` in `complexMessage` which can be used to reply to a message by providing its message id.
Example:
`{{ sendMessage nil (complexMessage "content" "This is a reply" "reply" .Message.ID) }}`
=> Added functions to reply to a message using custom command

customcommands/bot.go
Commit 3054fe9 (customcommands: handle responses over 2000 chars) via
PR #1294 introduced a regression with its automagic handling of responses
over 2000 characters, breaking custom commands reliant on the original
behaviour of dumping the code.
This commit attempts to fix that regression by adding a `-raw` switch so
that users relying on the original behaviour can force that for their
custom command """backend""", whilst we still keep a nice user-facing
experience.
Closes #1312
=> customcommands: add `raw` switch

common/templates/context_funcs.go
Previously, the `sendTemplate` function failed for threads with "unknown
channel". This commit modifies the tmplSendTemplate function as well as
the baseChannelArg function to also include threads.
Related suggestion:
https://canary.discord.com/channels/166207328570441728/356486960417734666/994956087142924438
=> customcommands: handle threads for `sendTemplate`

common/templates/general.go
`tmplJSONToSDict` would panic if the argument given to it was not a string.
This PR makes the func use the ToString function for the conversion of v instead of a type assertion.
=> cc: fix panic in tmplJSONToSDict

frontend/templates/cp_main.html
Occasionally, the offline shard checker runs during a routine restart and displays an irrelevant warning, confusing users. Avoid this by only showing an alert if a shard appears to be offline for two consecutive checks. (While we're at it, clean up the implementation.)
=> frontend: prevent spurious offline shard warnings

common/templates/general.go
The following code doesn't work currently:
```
{{addReactions (cslice "👋")}}
```
Instead, it displays an unintuitive error:
```
Failed executing CC #10, line 1, row 2: executing "CC #10" at <addReactions (cslice "👋")>: error calling addReactions: HTTP 400 Bad Request, {"message": "Unknown Emoji", "code": 10014}
```
The fix is simple, as shown, but why it makes a difference at all is a more complex matter. Below is a brief explanation for the benefit of reviewers and future readers of this code.
- `tmplAddReactions` defines a helper function `f`, which performs the actual API calls.
- `f` takes in a slice of `reflect.Value`s and calls `MessageReactionAdd(v.String())` for each value `v`.
- `reflect.Value.String` [returns a string of the form "\<T value\>" where T is v's …
=> templates: make callVariadic indirect inputs

automod/commands.go
"Violation: " removed from `/automod listviolationscount` embed. 
With a gentle shove from Mr. Ben, truncation of long Violation names was added. Emoji removal/unicode replacement was not implemented (seemed to be deemed unnecessary)
=> Implementation of Suggestion1981

moderation/commands.go
Having users joining, not able to identify how to enable moderation commands, and the error response failing to effectively indicate how to do so, has bugged me for a while. So this adds a link to the page for the given server, to the response...
=> Link to moderation configuration page

lib/dstate/interface.go
Because templates.CtxChannel aka .Channel has .Mention available, for consistency sake make it available also for dstate.ChannelState channels indexed from .Guild.Channels.
=> Mention method for dstate.ChannelState

rolecommands/menu.go
Similarly to linking to the moderation page when moderation commands are disabled, this adds a link to the Role Commands page, when there's a configuration issue, such as YAGPDB being unable to find a specified Role Group, or the Role Group having no Role Commands.
=> Link to Role Commands page

automod/automod_bot.go, logs/backgroundworkers.go, logs/logs.go
Logs use too much storage on YAGPDB.xyz, so this will place a 30d log and message restriction on it.
=> Restrict log to 30 days. 

stdcommands/define/define.go
When Urban Dictionary returns results without an author, this would error out the embed with no data for field value. This quickfix prevents this and will not remove Example, Author, Votes structure.
=> stdcommands: Define/Urban Dictionary embed fields fix for author field

stdcommands/forex/forex.go
fixed the bug where querying huge numbers (like more than 1,000,000 bananas) gives result for only 1 banana.
before: 
now:
=> fixed `Forex` Command bug, where more than a million in input was considered as 1 by API cuz float.

customcommands/tmplextensions.go
This PR adds support for switch args w/ parseArgs.
**Changes**
* A new function, `cswitch`, is added to enable defining switch arguments. Open to bikeshedding about the name, it's quite terrible but I was unable to think of something better. At least it's consistent with `carg`?
* `parseArgs` is slightly modified to support switch args during parsing.
* A new method, `Switch`, is added to the `ParsedArgs` struct to enable retrieving parsed switch args.
=> templates: add support for switch args w/ parseArgs

moderation/plugin_web.go
I noticed the status of the **Timeout** section, wasn't listed in the **Moderation** widget on the home page in the control panel, so this should add the status to that list, as well as including it in the overall display for whether the widget is enabled or not.
=> feat(moderation): Update moderation widget with Timeout status

moderation/commands.go
Updates the error message when attempting to run `/mute`/`-mute` without having a mute role selected, to direct users to the relevant configuration page.
=> feat(moderation): Update missing mute role error

moderation/punishments.go
The Template Script previosuly featured the check, `if .Reason`. But, `.Reason` returns the string, `"(No reason specified)"` if a reason wasn't provided when the moderation action was triggered, making this check redundant.
Additionally, the declaration of the constant used a multi-variable declaration style, for no dicernable reason, so this has been changed to a single variable declaration, and with the simplification of the Template Script, this commit also switches to using a single-line string, using the newline character.
=> refactor(moderation): Remove if from default DM

cah/commands.go, commands/yagcommmand.go, web/web.go, youtube/feed.go, youtube/youtube.go
This PR intends to address a pattern of repeated behaviour, following QoL updates made to the errors of some commands, linking to their configuration pages in the case of configuration errors.
This includes the addition of `web.ManageServerURL`, which encapsulates the behaviour for appending `/manage/SERVER_ID` to the result of `web.BaseURL`, as well as updating instance where this pattern was used previously, to use this new function.
These changes should also be applied to the changes of PR #1407.
=> refactor: Move config page URL formatting to `web.ManageServerURL`

common/templates/structs.go, lib/discordgo/structs.go, lib/dstate/helpers.go
This PR implements the `.Channel.OwnerID` object.
This returns `0` if the `.Channel` type is `GUILD_TEXT`
And the thread owners snowflake if the `.Channel` type is `PUBLIC_THREAD` or `PRIVATE_THREAD`
=> .Channel.OwnerID object (suggestion #2034)

stdcommands/forex/forex.go
Had to re-open this yet again because I PR'ed to the wrong branch after GitHub automatically closed the original Pull after I renamed my branches. So sorry for any hassle.
> This commit implements the requested clearer invalid currency code in #1383 by @jo3-l 
> Commit includes @Shadow21AR's updated embed which presents the `forex` response in a much cleaner look
> Couldn't push change to Shadow's branch so I had to create a new PR
> Forex response with clear notice that the currency code is invalid
=> forex: clear invalid currency code (#1383)

frontend/templates/cp_main.html
Add the server name to the tab title if a server's control panel is
open.
Though this is a rather small change, it is useful for those who have
multiple tabs open with different servers -- that way, one can easily
differentiate between open tabs.
I'm not sure how many actually do this, but it was bugging me enough to
whip up a patch, so that must mean something. :)
=> frontend: add server name to tab title

frontend/static/js/spongebob.js
Add a friendly note about dismissing PNotify alerts.
It isn't much, but a nice info to have nonetheless, QoL wise.
(I used to wait a while too until I figured you can click it to dismiss it)
=> frontend: add note about dismissing PNotify

stdcommands/forex/forex.go
1. there was a smol bug in query from my last PR (sorry), where converting 2 currencies with huge difference (inr & btc) was broken.
2. Fixed output to show numbers like 1,000,000 instead of 1e6 (idk what to call it, scientific notation?)
hopefully we stop playing ping pong with this command now xD
=> Forex stdcommands: fixed bug from my previous PR, changed the way numbers are shown

lib/dice/std.go
Return an error when user provides a zero-sided (D&D) die, preventing
the bot from panicking.
=> lib/dice: prevent panic from zero-sided die

rolecommands/menu.go
Minor edit, removing a forward-slash from a `fmt.Sprintf` string, which would cause the URL provided in an error to be invalid, leading to a `404` page.
=> fix(rolecommands): Fix invalid URL in cmd error

common/templates/general.go, lib/discordgo/message.go
This is a combination of two commits: ea8711a and db8e1d6.
Add the recently introduced `SUPPRESS_NOTIFICATIONS` message flag to
the set of `discordgo.MessageFlags`.
Also add a `Flags` field to both `MessageEdit` and `MessageSend` struct,
so that we can introduce a new key for `complexMessage` to suppress
notifications.
Add a "silent" key to complexMessage to suppress notifications.
Just recently a user on the support server asked whether it is possible
(with yagpdb) to use the new `@silent` feature -- standing now, that is
not the case.
So, I've gone ahead and implemented exactly that sort of feature. I'm
not expecting to have this released until the next scheduled release;
we've went quite some time without it, chances are that users can still
wait until the next release.
A minimal …
=> common/templates: add silent key to complexMessage

youtube/feed.go, youtube/web.go
This PR can be considered a continuation of #1466, and aims to address the issues I highlighted in a comment on that PR.
Notably, this moves the fetching logic previously handled by `Plugin.getYtChannel`, behind the `ytChannelID` interface, and a series of newtypes which will handle determining the fetching logic used. By having `Plugin.parseYtUrl` return `ytChannelID`, it becomes more appropriate for `Plugin.HandleNew` to call the method directly, thereby avoiding flattening fetching errors, with URL parsing errors, improving error reporting to end users, as well as entirely removing the need for `Plugin.getYtChannel`, the `ytUrlType` type, and its associated constants. With this change, some of the fetching logic used has also been optimised, such as using the `youtube.VideosService` to …
=> refact(youtube): Decouple channel fetching and URL parsing logic

youtube/feed.go
Apparently the YouTube search API doesn't like it up channel handles are escaped in a query, so this removes the use of `url.QueryEncode` in `searchChannelID.getChannelList`...
=> fix(youtube): Remove escape in channel query

youtube/feed.go, youtube/web.go
This is a brief PR to add support for parsing `youtube.com` URLs with the `playlist` path, and fetching channels based on the playlist ID parsed. Consequently, this adds the `playlistID` newtype, and accompanying `playlistID.getChannelList` method, based on the `youtube.PlaylistService` type.
=> feat(youtube): Add playlist URL support

lib/template/exec.go, lib/template/exec_test.go
The following program
```
{{try}}{{return}}{{catch}}{{end}}BAD
```
currently outputs `BAD` — the return inside the try action is erroneously swallowed. (A similar issue occurs with returns in the catch list.)
This PR addresses this issue by properly propagating control flow signals in `walkTry`, and adds a couple tests to ensure correctness. The patch is slightly complicated by the need to return from a deferred function — to do so, we introduce a named return variable and assign to it as needed.
=> template: don't swallow returns in try-catch actions

frontend/templates/cp_nav.html
For logged in users, favour the global_name they have set, otherwise use
their username in the account box.
This change is fully backwards-compatible. Users without their display
name set will continue to see their username; users with a pomelo name
and no display name will obviously see their pomelo name instead.
See: Suggestion No. 2091
https://discord.com/channels/166207328570441728/356486960417734666/1116722286989426758
=> frontend: favour globalname for logged in users

notifications/assets/notifications_general.html
Add character count labels to the leave and join messages on the control
panel.
In the past, it was quite frustrating to not know how many characters
you have left. Also, it was a suggestion on the support server, see
here:
https://canary.discord.com/channels/166207328570441728/356486960417734666/1095153342176579777
=> frontend: add char count to leave/join messages

lib/discordgo/endpoints.go, lib/dstate/interface.go
I've noticed during testing with an animated guild icon that
`.Guild.IconURL` *always* returns a static png. It can be argued that
this is a sort of regression in comparison to the old way, which #1519
attempted to get rid of.
Unfortunately I wasn't able to test with an animated guild icon during
the development of the above mentioned pull request ~~because I refuse
to give Discord money~~, because such a guild wasn't available to me at
that time.
I've decided to implement a new endpoint in discordgo that returns the
gif version of the guild icon. Furthermore, I've modified dstate's
GuildSet.IconURL to make use of that new endpoint if it finds indication
that the guild icon is animated.
It'd be really cool if we can get this in before the scheduled release on
monday as a sort of hotfix, …
=> lib: fix always returning png in gs.IconURL

common/util.go, customcommands/bot.go, stdcommands/customembed/customembed.go
Allow codeblocks and YAML to be used in the `customembed` command.
Users will now be able to invoke the command with a codeblock wrapped
around their JSON or YAML, which makes writing and reading said data
quite a lot easier.
This change is fully backwards-compatible.
Here's an example of the new usage:
----
This is a combination of two commits:
* common/util: export ParseCodeblock func
Export the ParseCodeblock function in common util, moving it out
from its unexported location in customcommands.
We'll be using this later for the customembed command and honestly
it should have been exported from the get-go.
* stdcommands/customembed: allow codeblock and YAML
Allow Discord codeblocks to be used in the customembed command. For
bonus points, also allow YAML to be given instead, falling back …
=> stdcommands/customembed: allow codeblock and YAML

CONTRIBUTING.md
Improve the contributing guidelines to be even clearer on how to suggest
new features and how to open a pull request.
Also point out that commit messages and/or PR titles should be
descriptive and should include a small description of the patch.
=> meta/contrib: improve contributing guidelines

frontend/static/js/spongebob.js, frontend/templates/cp_main.html
Link to the relevant incident page when we are forwaring an incident
from Discord on the control panel, so there isn't much left to ask.
Relevant suggestion on the support server:
https://discord.com/channels/166207328570441728/356486960417734666/909083451704115231
=> frontend: link to Discord statuspage for incidents

autorole/assets/autorole.html, autorole/autorole.go, autorole/bot.go
Add an option to ignore bots from autorole assignment. This is a really
popular suggestion on the support server -- link below.
https://discord.com/channels/166207328570441728/356486960417734666/992525415405072414
----
P.S.: I'm not sure if this patch is good as-is; I tried to follow the
currently existing control flow by just adding the required check
where-ever similar control structures are present.
Local testing confirm it is working (though I did not test with
membership screening).
=> autorole: add option to ignore bots

reminders/plugin_bot.go
Based on unofficial suggestion here https://discord.com/channels/166207328570441728/525535451839463424/1132563547864440922 This pr changes some reminder commands to give ephemeral responses when used with the slash command. `reminders`, `creminders`, and `delreminder` are now ephemeral to respect user privacy. The `remindme` command was intentionally left out, hopefully to remind users that their reminders can not, and will not be ephemeral. I considered adding an additional notice to the `reminders` command illustrating this, would love to hear thoughts on the matter.
Additionally, it adds a response to `reminders` and `creminders` for when no reminders are found, as opposed to the current version which sends the prefixed and affixed messages with empty space in between.
Draft because I …
=> reminders: Add privacy and cleaner empty reminder response

lib/discordgo/message.go, lib/discordgo/structs.go
Add a new MessageActivity type to the Message struct.
This MessageActivity type represents the activity sent with a message,
commonly referred to as an invite to a game session and such.
This is a suggestion on the support server, found here:
https://discord.com/channels/166207328570441728/356486960417734666/1125192216650977360
=> lib/discordgo: add activity to message struct

common/templates/context.go, customcommands/bot.go
This pr simply trims leading and trailing whitespace from custom command response before validating the character count. Since Discord would do this anyways, leading and trailing whitespace does not count towards it's 2000 character limit, and therefore imo should not throw an error for response length.
Of course it is still good practice for users to trim space within the code itself, especially when printing to the response within a `range` function, or even simply in multiple lines along the code.
I understand that this pr may encourage some users to learn bad habits and not trim their own whitespace when using `range`, however I believe it is already difficult for users to understand the concept of the `range` function generating whitespaces since, as aforementioned, Discord trims …
=> custom commands: Trim whitespace on response before character count validation

customcommands/bot.go
This PR addresses issues noted here: https://discord.com/channels/166207328570441728/871323274066407454/1131615601937371177 and here: https://discord.com/channels/166207328570441728/525535451839463424/1132267904033894451, where Dcmd is messing with the sender's snippet while parsing the argument. The two examples I've seen so far are with backslash tokens and container trimming. Summary to my understanding:
Evaluating `{{ "\s" }}` with evalcc fails for "invalid syntax," which makes sense because `\s` is not a valid character. However, when trying to escape the backslash, with `{{ "\\s" }}`, the intended output would be a string that reads "\s", however again this fails due to invalid syntax. Evidently yag is still attempting to evaluate `\s` despite the attempts to escape the backslash. I …
=> evalcc: Bypass dcmd argument parsing

lib/discordgo/endpoints.go, lib/discordgo/structs.go, lib/dstate/helpers.go, lib/dstate/interface.go
Add the Banner field to discordgo.Guild and dstate.GuildSet structs,
thus exposing them to custom commands.
Furthermore add a BannerURL method on dstate.GuildSet, returning the
appropriate URL (animated/static) to the Banner.
A relevant suggestion can be found here:
https://canary.discord.com/channels/166207328570441728/356486960417734666/992995802093981726
=> lib/{dstate,discordgo}: add Banner to Guild struct

customcommands/tmplextensions.go
Properly cap multiple database interactions at the documented maximum of
100 affected entries.
Without this change, Custom command code such as the following would be
able to circumvent the documented max limit of affected entries:
```
{{ dbDelMultiple [...] 0 0 }}
```
This code would affect as many entries as are matching defined by the
(for brevity omitted) query argument to this and related functions.
Clearly this is a bug — We deliberately limit interactions with the
custom commands database to *at most* 100 entries at a time, users being
able to bypass this is at best a simple oversight, at worst able to
bring the bot down due to high database load.
As for why/how this works, from the PostgreSQL documentation:
> If a limit count is given, no more than that many rows will be
> …
=> customcommands: properly cap multi queries at 100

customcommands/assets/customcommands-editcmd.html, customcommands/web.go, frontend/static/css/custom.css, web/template.go
Grey out the trigger on edit checkbox on non-premium servers. The backend already does this; I just thought it might be nice to have an additional visual cue.
Appearance on dark and light mode respectively:
=> cc/web: grey out trigger on edit toggle if not premium

lib/discordgo/endpoints.go, lib/discordgo/user.go
In introducing the new username system, Discord also switched to a different indexing scheme for default avatar URLs. In particular, per https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints:
> For users on the new username system, `index` will be `(user_id >> 22) % 6`.
This PR thus adjusts `User.AvatarURL` to account for this, aligning the output of `User.AvatarURL` with what is displayed on Discord.
=> discordgo: correct default avatar URLs

README.md
Get rid of the diffstat artefact introduced in 8ce2df141c00, restoring
the original text on that line.
The mentioned commit introduced some diffstat artefacts, hiding the
original text, presumably due to some copy-paste mistakes (they can
happen, no worries).
Thanks to git being very cool with regards to storing history, I was
able to restore the original text that was there. Kinda weird that
nobody bothered to fix it so far.
=> readme: get rid of diffstat artefact

README.md
Bump the minimum required Go version to ^1.20, as per `go.mod`:
https://github.com/botlabs-gg/yagpdb/blob/60fb9d292843bdac0cadbbf53accac42a7f77eaf/go.mod#L3
=> readme: bump Go version req to ^1.20

lib/discordgo/structs.go
Currently it is not possible for the user to retrieve **camera** or **go-live activity** in a guild's voice channel (by using **.Guild.VoiceStates**), although discord allows this as documented [here](https://discord.com/developers/docs/resources/voice#voice-state-object).
This PR should  fix that.
=> Adding "self_video" and "self_video" to VoiceState in structs.go

lib/template/exec.go, lib/template/exec_test.go
This PR adds the ability to range over a number (i.e. ints and uints) in template.
```
{{range $k, $v := 2}}{{$k}}{{$v}}{{end}}
```
Should print `0011`
```
{{range 2}}{{.}}{{end}}
```
Should print `01`
```
{{range 0}}{{else}}empty{{end}}
```
Should print `empty`
```
{{range -1}}{{else}}empty{{end}}
```
Should throw an error
=> lib/template: allow range over number

lib/discordgo/structs.go
It isn't used by the bot, and in some rare instances causes panic when some servers have custom application ids.
=> Removed application_id from Game 

reddit/assets/reddit.html, reddit/models/reddit_feeds.go, reddit/plugin_web.go, reddit/redditbot.go, reddit/schema.go
This pr adds a toggle to enable wrapping reddit posts in spoilers, as suggested in [suggestion #2022](https://discord.com/channels/166207328570441728/356486960417734666/1050921841599979550). Currently Yag will spoil anything marked by the poster as a spoiler, this toggle would allow users to disable this. This value defaults to enabled to maintain current functionality.
I cannot get reddit working on my self host, so I cannot demonstrate this feature. I originally wrote this code in December, and subsequently re-wrote it in August, and am now pr'ing in October because I am not like other girls.
=> reddit spoiler usage toggle

automod/automod_web.go, automod_legacy/web.go, frontend/templates/cp_nav.html, logs/web.go, moderation/plugin_web.go, verification/verification_web.go, web/web.go
Move subpages relevant to moderation to their own tab in order to
declutter the Tools & Utilities category on the control panel.
Seeing as Tools & Utilities is one of the largest cagetory on the
control panel, it can be viewed as a "catch-all", which is undesirable.
See also suggestion 2148.
https://discord.com/channels/166207328570441728/356486960417734666/1163826271231418380
=> frontend: move moderation pages to their own tab

logs/web.go
Users have continually expressed confusion regarding the error used
when attempting to open a message log for a server,
where logs are restricted to members only.
The current message implies the user isn't a member of the server,
even if they are.
This pull request attempts to rectify this, by adding a prompt
suggesting the user should use the provided login link, if they are a member.
=> feat(logs): Add login prompt for members only logs

bot/util.go, lib/discordgo/gateway.go, lib/discordgo/structs.go, lib/dstate/helpers.go, lib/dstate/interface.go, stdcommands/setstatus/setstatus.go, streaming/bot.go
Implementing custom status type so that `-setstatus` will use custom status instead of Playing... now that it's available to bots
Flags have been added to permit the user to choose the presence type and online status of the bot
`GameType` has been renamed to `ActivityType`
`ActivityTypeCustom` and `ActivityTypeCompeting` have been added to the ActivityType struct
`UpdateStatus` now uses `ActivityTypeCustom` by default
`UpdatePlayingStatus`, `UpdateWatchingStatus`, and `UpdateCompetingStatus` have been added
`Update*Status` have had their parameters adjusted to allow the user to set online/idle/dnd/offline
Two new fields have been added to the Redis DB to store chosen presence type and online status.
Also thanks @l-zeuch for helping test and then helping me set up selfhost so I could test …
=> Implement custom status type

customcommands/assets/customcommands_database.html, customcommands/customcommands.go, customcommands/web.go
Add a database view page to the control panel, allowing users to view
their custom command database, and, as necessary, search for entries
matching specific criteria.
The output is, no matter the request, paginated to max 100 entries per
page, which is in-line with the maximum one can achieve via a `dbGetPattern`
call in custom commands.
I've also decided to add delete functionality for individual entries,
such that if a stray entry that is no longer needed is found, it can be
deleted without resorting to a custom command / `evalcc`.
=> customcommands/web: add database view page

customcommands/assets/customcommands_database.html, customcommands/tmplextensions.go
Add (approximate) Size to the LightDBEntry struct, set to the length of
the raw byte value.
It should be noted that, although this reading may be inaccurate,
internally we already limit the raw byte value to 100_000 in length;
thus, this change (and by extension this reading) is consistent with how
entry size is already determined.
As an added bonus, and because it was requested in
botlabs-gg/yagpdb#1590, I've also added the size reading to the therein
introduced view page.
I believe to recall that such a thing was either suggested in
`#suggestions`, or that it was requested in a drive-by comment in one of
the help channels; but I cannot find either.
=> customcommands: add Size field to LightDBEntry

common/templates/context.go, common/templates/context_funcs.go, lib/cardsagainstdiscord/game.go, lib/discordgo/components.go, notifications/plugin_bot.go
Change discordgo.Button.Emoji to *discordgo.ComponentEmoji and include
the omitempty tag.
Discord no longer allows the `emojis` field in button objects to be
null, and instead require it be absent. This commit adds the "omitempty"
tag to the Emoji field, and changes the value to a pointer.
See also the suggested fix from the Discord Gophers server:
https://discord.com/channels/118456055842734083/155361364909621248/1192299819012722748
=> discordgo: fix button message component emoji errors

cmd/yagpdb/main.go, common/config.go, common/util.go, trivia/questions.go, trivia/trivia.go, trivia/trivia_bot.go, trivia/trivia_commands.go, twitter/twitter.go
Sends a random question from opentdb.com, and records all answers sent within 10 seconds, and shows the list of winners.
=> Added Trivia

web/middleware.go
The PR fixes a typo in the warning alert by changing "can not" to "cannot"
=> web/middleware: change "can not" to "cannot" in warning alert

lib/discordgo/message.go
Allow accessing relevant super reaction data (for instance, via `.Message.Reactions` in custom commands), as requested in the popular suggestion no. 2114 on Discord.
=> lib/discordgo: expose super reaction data

logs/logs.go
Previously, if channel A was blacklisted, the logs command could still be used in subthreads of channel A (though not channel A itself.)
Thanks to wroclaw on Discord for reporting this bug.
=> logs: don't create logs in threads of blacklisted channels

frontend/templates/cp_core_settings.html
Remove the beta notice for the control panel read access setting, as it
is certainly to be considered stable by now.
Definitely a small and very minor change, but I noticed it whilst I was
browsing the control panel for something else.
=> frontend: remove beta notice for read access

common/templates/context.go, common/templates/context_funcs.go, common/templates/structs.go, lib/discordgo/structs.go, lib/dstate/helpers.go, lib/dstate/interface.go
Continuation of #1604 and #1453 
This PR does two things:
* Updates discordgo, dstate with new fields related to forums (available tags, applied tags, default thread rate limits, etc.)
* Adds `createForumPost` and `deleteForumPost` templates
Other Info:
* Limits for create and remove are currently shared with thread's create and remove limits
* Optional args for `createForumPost` are set to use key-value style so that order doesn't matter and we can also expose other optional args later
API (templates):
Field | Description
--- | ---
.Channel.IsForum | true if channel is forum type
.Channel.AvailableTags | Slice of discordgo.ForumTag. Only present if channel is forum type.
.Channel.AppliedTags | Slice of int64 representing tag ids. Only present if channel represents a specific forum …
=> Add Forum Post Support

reputation/plugin_bot.go
When you add channels for 
**Whitelisted channels for giving rep using thanks** 
or 
**Blacklisted channels for giving rep using thanks**
in reputation in `/manage/server_id/reputation` page
Bot still allows in threads in blacklisted channels
Bot doesn't work in threads in whitelisted channels
=> fix: thanks detection logic for blacklist/whitelist

customcommands/bot.go
Populate templates.Context's Msg field with a copy of the triggering
message that launched evalcc.
This bug was caught via my own testing; I was looking to launch replog
via exec and used evalcc for that — it did not work. The reason is, that
the exec (and by extension the execAdmin) logic make a copy of
templates.Context.Msg, which was never populated.
By populating it, we ensure that the exec logic has a message to work
with and thusly cooporate as expected with restricted inbuilt commands
like replog.
This is defintely a bug, given how evalcc is supposed to behave *almost
like* a normal custom command.
=> customcommands: populate ctx.Msg in evalcc

tickets/tickets_commands.go
fix typo `attatchment` -> `attachment`
I'm a mod in a server that uses tickets heavily for moderation and often puts screenshots in them. Seeing this typo just bothers me all the time I'm backreading ticket logs
=> Update tickets_commands.go: fix typo

customcommands/bot.go
Link to the CC's corresponding edit page on the dashboard when examining a single CC with the CustomCommands command. The link is masked by the CC ID so the user-facing response doesn't get any more bulky.
Also suppresses embeds so said links do not become embeds.
Signed-off-by SoggySaussages <vmdmaharaj@gmail.com>
=> customcommands: link to ccs in cc command

lib/discordgo/restapi.go, moderation/punishments.go
It was recently noted that the YAGPDB was not setting an audit log reason, when kicking users via command, or when unbanning users. This first of these, was due to the fact the relevant method was based on an old API design, and hadn't been updated, and the second because the relevant method didn't exist.
This PR fixes both of these issues, by adding the relevant method, as well as updating the existing one to use the `X-Audit-Log-Reason` header, rather than the old query string method.
=> fix: Clean-up usage of X-Audit-Log-Reason

common/templates/context_funcs.go, common/templates/general.go
function signature is now: 
```
createThread channel messageID name (private) (auto_archive_duration) (invitable)
```
Example Usage
```
{{createThread nil nil "Test Thread" true 61 true}}
```
=> Added optional args `auto_archive_duration` and `invitable` to createThread

common/templates/context_funcs.go
As suggested in #dev-discussion, permit the `sort` template function to index (exported) struct fields, so that code like
```
{{ sort .Guild.Roles (sdict "key" "Position") }}
```
just works, instead of erroring with `cannot index value of type discordgo.Role`.
Note that the proposed patch still does not support niladic method calls. Hence, code like `{{ sort $sliceOfTimes (sdict "key" "Hour") }}` remains an error, since `Hour` is a method on `time.Time`, not a field. Ideally, we would lift this restriction and completely align the implementation of the `key` option with field access in templates, such that `{{ sort $xs (sdict "key" "K") }}` corresponds to sorting by `$x.K`. This behavior, however, is much more difficult to implement so is not done in this PR (and it is debatable whether …
=> templates: permit sorting by struct key

soundboard/transcoder.go
The soundboard module formerly used gorm, but was migrated to sqlboiler some years ago in https://github.com/botlabs-gg/yagpdb/commit/628ea9a228ab11dcc327ad0d017c5654312025af. There are still two (erroneous) references to gorm remaining which were not caught since this section of code ignores errors. This PR changes these to use sqlboiler as well.
This PR is marked as a DRAFT since I do not yet have soundboard set up locally, so have not tested this change. It is put up so that 1) I don't forget about it and 2) in case any folks who do have soundboard working have time to test and report their findings. If not, I will set up soundboard eventually and verify that this PR works.
=> soundboard: remove stray references to gorm

common/schemamigration.go
YAGPDB currently uses a bespoke database migration system that works as follows. For each database migration (called a "schema" internally), we try to classify (by testing a set of regexes against the SQL) the migration as doing one of the following:
- creating a new table,
- adding a new column to a table, or
- adding a new index on a column.
If the migration is not recognized as any of the above types, it is run. Otherwise, to avoid gratuitously executing migrations, we check some database metadata to see if the migration is necessary. For instance, if the migration is creating a table, then we query `information_schema.tables` to see if the table already exists. If so, the query is skipped.
This process is somewhat effective: it successfully detects (and thus skips) most migrations …
=> schemamigration: skip executing ALTER COLUMN SET NOT NULL queries when possible

customcommands/assets/customcommands-editcmd.html
Refactor the JS script for the custom command edit page to be more maintainable and extensible.
As noted previously in https://github.com/botlabs-gg/yagpdb/pull/1619#discussion_r1517164374, the current JS script for the custom command edit page has grown rather complex and difficult to understand over time. Particularly egregious is the current logic for showing/hiding various parts of the page depending on the trigger type:
https://github.com/botlabs-gg/yagpdb/blob/447a52732f5b901314397fe9079290e59d9f8d45/customcommands/assets/customcommands-editcmd.html#L536-L613
Though avoiding overabstraction is important, the sheer repetitiveness and density of this code (~80 lines with very minor differences between if branches, obscuring the function of the code) renders it extremely difficult to …
=> cc: restructure edit page JS for improved maintainability

frontend/static/js/spongebob.js
This PR fixes the following bug (thanks to galen for discovery): clicking the delete button beside a custom command response and then cancelling it at the confirmation popup (erroneously) still deletes the response. Screencapture below.
https://github.com/botlabs-gg/yagpdb/assets/56809242/67788466-c0ee-4584-b44b-f130b02c4c4e
An analysis of the issue: the confirmation prompt is triggered when any element with the `btn-danger` class is clicked. If confirmation fails, preventDefault() and stopPropagation() are called, which are typically sufficient to prevent the deletion from going through. But in the case where the deletion is performed in another click event handler -- which is the case for the implementation of deleting custom command responses -- stopPropagation() will (roughly …
=> frontend: don't trigger other event handlers if delete action cancelled

commands/tmplexec.go
Also return `*discordgo.MessageSend` after executing a command via a
fake message.
Commit 97b021dd6815 ("customcommands: link to ccs in cc command ") via
PR #1624 introduced a side effect where constructs such as
`{{ exec "cc" "1" }}` no longer worked, thus resulting in breakage.
This patch does *not* fully restore the former state, however seeing as
the aforementioned commit broke things in a very subtle way it seems
acceptable to introduce a new, different behaviour.
Admittedly, with the current state of in-built commands responding with
all sorts of things that may or may not be writable to a CC variable,
this only confuses things further, but at least it is working again(TM).
At some point in the future we could consider sorting these
"inconsistencies" out and making it "just werk" …
=> commands/tmplexec: also return `*discordgo.MessageSend`

common/keylock/keylock.go, common/keylock/keylock_test.go, customcommands/bot.go
This PR improves the type safety of the `common/keylock` package by making `KeyLock` generic over the key type (previously `interface{}`), which also slightly improves performance*. For context, I was looking over `common/keylock` to see whether we could replace the muted user lock in https://github.com/botlabs-gg/yagpdb/blob/master/moderation/mutelock.go with a `KeyLock`, given the two pieces of code implement largely the same thing. (It turns out we can, but I'll defer this change to a later PR once the sqlboiler changes to the `moderation` plugin are complete.)
*`benchstat` results:
```
goos: linux
goarch: amd64
pkg: github.com/botlabs-gg/yagpdb/v2/common/keylock
cpu: 11th Gen Intel(R) Core(TM) i9-11900T @ 1.50GHz
│   old.txt    │               new.txt               │
│    sec/op    │ …
```
=> keylock: make KeyLock generic and improve documentation

automod/conditions.go, automod/rulepart.go
This update adds 2 new AMv2 conditions: message with attachments and message without attachments.
Allows for situations where you want to trigger on new or edited messages only if they do (or don't) contain attachments. Example provided in the suggestion was "allow the trigger `Message with less than x characters` to prevent spam without affecting attachment only messages."
=> Adds with/without message attachments conditions (Suggestion 2208)

stdcommands/cleardm/cleardm.go, stdcommands/topcommands/topcommands.go
updated the `cleardm` command description to match the other Bot Owner only commands.
updated the `topcommands` command description to include `Bot Admin Only` in the description.
=> cleared up owner and bot only commands

moderation/commands.go
The current implementation of the `clean` command is somewhat difficult to follow: depending on the arguments, we set about 10 different variables and pass them to `AdvancedDeleteMessages` as arguments:
https://github.com/botlabs-gg/yagpdb/blob/736d1b388602789a1d99731c10cd6240a18e9f7f/moderation/commands.go#L751
(`AdvancedDeleteMessages` subsequently checks each filter one-by-one in a long series of conditionals, but this code is not particularly problematic; it is just long, but is relatively easy to understand.)
This PR refactors the code by introducing a `Filter` interface (which, given a message, reports whether it passes the filter); each filter is a separate struct implementing this interface. The main `clean` code then boils down to building a slice of `Filter`s based on the …
=> moderation: refactor clean command

lib/dcmd/data.go, lib/dcmd/response.go, stdcommands/poll/poll.go, stdcommands/wouldyourather/wouldyourather.go
Related to #1671. This PR allows poll and wyr responses to be autodeleted after a delay via command overrides. Previously, the command system had no knowledge of responses to these commands (which are sent manually since reactions need to be added), so autodeletion did not work.
=> poll,wyr: obey response autodeletion set via command overrides

bot/paginatedmessages/paginatedcommand.go, bot/paginatedmessages/paginatedinteractions.go, commands/help.go, logs/plugin_bot.go, moderation/commands.go, reputation/plugin_bot.go, stdcommands/define/define.go, stdcommands/dictionary/dictionary.go, stdcommands/forex/forex.go, stdcommands/howlongtobeat/howlongtobeat.go, stdcommands/inspire/inspire.go, timezonecompanion/plugin_bot.go
Currently, commands with paginated responses do not obey the 'delete response after delay' option set using command overrides. So, for instance, if one creates a command override for the `HowLongToBeat` command, configures it to autodelete after 5 seconds, and then runs `-hltb ... -p`, the paginated message will *not* autodelete.
The reason for this odd behavior is that dcmd (and in turn the YAGPDB command system) does not know about paginated messages — which are sent manually as opposed to using dcmd's response mechanism — and so naturally does not delete them.
This commit therefore teaches dcmd about paginated messages by introducing a new type, PaginatedResponse, which implements dcmd.Response. When returned from a command run function, dcmd will automatically call …
=> paginatedmessages: interoperate with response autodeletion setting

commands/util.go, commands/yagcommmand.go, reminders/plugin_bot.go
Previously, if a member used `remindme ... -channel #foo` and `remindme` was disabled via command/channel overrides in channel `#foo`, the command would still go through as long as the member had send message permissions in `#foo`. This PR fixes `remindme` to check command overrides as well.
=> reminders: verify that member can run `remindme` in target channel

automod/effects.go, automod_legacy/bot.go, commands/commands.go, commands/tmplexec.go, common/templates/context.go, customcommands/tmplextensions.go, moderation/commands.go, moderation/plugin_bot.go, moderation/punishments.go, tickets/tickets_bot.go, tickets/tickets_commands.go, tickets/tmplextensions.go, verification/verification_bot.go
This PR blocks looping `exec` or `execAdmin` on commands which parse a template (such as moderation actions' Punish
DM or the opening message in a ticket).
Upon executing one of these commands, a new context flag marks it as executed from a command template. If within this 
new template one of these commands is used again, its context gets a flag marking it as executed from a *nested*
command template. Any of the functions executed within a nested command template will fail.
This PR also blocks using `execCC` within any of these commands' templates. This will likely soon be mollified by the addition of an 'autoScheduleExecCC' function suggested by @jo3-l which will allow users to once again execute CCs
within these commands' templates in a manageable and rate limited fashion. …
=> templates: block nested template executors

stdcommands/simpleembed/simpleembed.go
Don't clear out the embed title when editing it via `simpleembed`.
Because we provide an empty default value for the title field, it is set
to that if no "new" title is given when using this command to edit said
embed.
=> stdcommands/se: don't clear out title when editing

common/templates/context_funcs.go, lib/discordgo/restapi.go, lib/discordgo/structs.go, lib/dstate/interface.go
Fix the following bugs:
- createThread auto archive duration argument not impacting the created thread
- createThread not able to create announcement threads
- editThread and closeThread not able to alter announcement threads
- typo in create/editThread error
=> cc/threads: fix a few more bugs

customcommands/tmplextensions.go
This PR relaxes a restriction on `execCC` calls from command templates (e.g., moderation DM templates) introduced in #1677. Specifically, we now permit one `execCC` call from command templates as long as it is not nested. This new restriction still resolves the original issue that #1677 set out to address but is less prone to cause breakage in userland.
=> customcommands: relax restriction on execCC from command templates

customcommands/assets/customcommands-editcmd.html, customcommands/assets/customcommands.html, customcommands/bot.go, customcommands/models/custom_command_groups.go, customcommands/models/custom_commands.go, customcommands/schema.go, customcommands/tmplextensions.go, customcommands/web.go
- Small warning if the command group is disabled
- A switch for disabling the custom commang group
[Suggestion #2224](https://discord.com/channels/166207328570441728/356486960417734666/1246836065872908298)
=> Disable custom command groups (Suggestion #2224)

common/templates/structs.go, lib/discordgo/structs.go, lib/dstate/helpers.go, lib/dstate/interface.go
Add the `ThreadMetadata` properly to `discordgo.Channel`, that is,
remove the flattened duplicate entries from said struct and instead keep
just `discordgo.ThreadMetadata`.
As a consequence, this cascades to dstate as well as common/templates,
which were modified to reflect that change; as an added bonus, this now
properly represents the channel structure as defined by Discord, rather
than a custom flattened one.
BREAKING CHANGE:
`.Channel.{Locked,Archived}` will be moved to `.Channel.ThreadMetadata.*`.
Migrate by adding that additional layer to your accessing of these
fields. Reports indicate this hasn't worked properly anyway, therefore
this breakage should be acceptable.
=> lib/discordgo: properly add ThreadMetadata

automod/automod_bot.go, automod_legacy/bot.go, moderation/punishments.go
This PR is one of several aiming to mitigate the impact of bugs similar to those introduced in the previous release.
The most pressing issue was the inadvertent removal of a nil guard in `KickUser` by me in #1659, which caused panics which were difficult to track down. To make these easier to debug in future (and to prevent complete bot crashes), in this PR we recover and log a stacktrace for panics in applying advanced automod effects and basic automod punishments. This supercedes the temporary bandaid recover added directly to `KickUser` in https://github.com/botlabs-gg/yagpdb/commit/f9602a1bb41ea1e86e2c6dfb06b8dd69998dba69.
For reference, I compiled a version of the bot with the nil pointer bug re-added (but with this patch applied as well.) Instead of crashing, the following is logged …
=> automod: recover from panics in applying effects

notifications/config.go, notifications/plugin_bot.go, notifications/plugin_web.go
This PR is a one-to-one mirror of #1696 for the notifcations package. Please read the description of that PR for details.
=> notifications: explicitly separate config functions that access bot process cache

automod/automod_web.go, moderation/commands.go, moderation/config.go, moderation/moderation.go, moderation/plugin_bot.go, moderation/plugin_web.go, moderation/punishments.go
This PR is one of several aiming to mitigate the impact of bugs similar to those introduced in the previous release.
Another issue introduced (again, by me) in the previous release was that the web handlers for both the moderation and notifications packages called `GetCachedConfig` instead of `GetConfig`. `GetCachedConfig` is only meant to called in the bot process; using it in the web process caused the following cache invalidation issue:
1. `GetCachedConfig` in web process creates a config cache on the web process, separate from that maintained on the bot process.
2. When changes to the config are saved via the control panel, a pubsub event indicating that the config cache should be invalidated is fired.
3. However, only the bot process is configured to handle pubsub events, so only the …
=> moderation: explicitly separate config functions that access bot process cache

tickets/tickets_commands.go
Improve the "Missing Access" error message when trying to send a
ticket's transcript and/or images to the ticket logs channel.
Currently, the bot simply responds with a quite generic "Missing Access"
error, which, whilst technically correct, isn't exactly helpful.
Therefore, send a proper error instead that explains what went wrong and
that we're refusing to close the ticket for exactly that reason.
=> tickets: improve Missing Access error message

lib/dstate/interface.go
Please note that this patch is ~~entirely~~ partially untested on my part, 
because I lack a member boosting the server ~~and one with flags set.~~ I have
reasonably high confidence that this will work, but I cannot guarantee
it.
Fully populate the discordgo.Member struct in ms.DgoMember(); prior to
this change, this function did not set PremiumSince nor Flags, thereby
rendering these fields effectively useless in custom commands.
They are present everywhere else, and are documented in our custom
command documentation as available, so it appears as if these fields
have been left out by accident, rather than on purpose.
=> dstate: fully populate member struct

frontend/templates/cp_main.html, web/handlers_general.go, web/web.go
Review commit-by-commit.
This PR makes the following changes:
1. Add and use a per-guild status endpoint, `/api/:server/status.json`, that returns `{"shard_online": true/false}`. Switching to this endpoint decreases the data sent over the network from ~400 kB to ~20 B (a 10000x reduction.)
2. Introduce a more robust fix to the 'spawning one interval per page' issue, superceding https://github.com/botlabs-gg/yagpdb/commit/b9dabf9eba7d45c1189b695c55076f3f9669c022. The problem with https://github.com/botlabs-gg/yagpdb/commit/b9dabf9eba7d45c1189b695c55076f3f9669c022 is that it uses `sessionStorage`, which is not cleared on refresh. But this is overkill: we actually *need* the offline shard checker to run upon refresh, since the old intervals are cancelled on refresh. To see the issue, open …
=> web: optimize offline shard checker

customcommands/assets/customcommands-editcmd.html, customcommands/assets/customcommands-public.html
The backend validation for custom command response length checks the number of runes (that is, Unicode code points) in the input:
https://github.com/botlabs-gg/yagpdb/blob/b9dabf9eba7d45c1189b695c55076f3f9669c022/customcommands/customcommands.go#L157
However, the frontend character counter reads the `length` field of the response JavaScript String, which measures UTF-16 code units. The number of Unicode code points is not necessarily equal to the number of UTF-16 code units, occasionally producing a confusing discrepancy between frontend and backend. To demonstrate the issue, create a new custom command and run the following in console:
```js
$('.cc-editor').val('😨'.repeat(5001)); // 😨 is encoded as 2 UTF-16 code units but is one code point
onCCChanged(); 
```
The character counter …
=> customcommands: align frontend length display with backend validation

customcommands/bot.go, moderation/commands.go, reputation/plugin_bot.go, rolecommands/menu.go, tickets/tickets_commands.go, web/web.go
Review commit-by-commit.
Add a new debug command, `DiagnoseCCTriggers`, that lists all custom commands triggering on its input and identifies potential issues. The intent is for support members to instruct users to run `DiagnoseCCTriggers` in the event of custom commands not triggering as the user expects; we can also consider adding a note in the documentation and/or control panel pointing to this command where appropriate.
Sample output:
To implement `DiagnoseCCTriggers`, some light refactoring to enable code reuse was necessary (see first 3 commits.)
In the server, Henri proposed that, instead of a command, a control panel warning could be generated when there are conflicting triggers. Though such a warning would definitely be more discoverable, it is difficult to implement--requiring …
=> cc: implement new DiagnoseCCTriggers command

customcommands/assets/customcommands-database.html, frontend/static/js/spongebob.js
Currently, if you change any of the search parameters on the custom command database page, the unsaved changes popup shows up (and clicking save confusingly redirects you to the home page.) The reason, of course, is that--unlike many other forms on the control panel--the search form is not meant to be POSTed to. Hide the unsaved popup for the search form to avoid any confusion.
=> cc: do not show unsaved popup on database page

automod/effects.go, automod_legacy/bot.go, commands/commands.go, commands/tmplexec.go, common/templates/context.go, customcommands/tmplextensions.go, moderation/commands.go, moderation/plugin_bot.go, moderation/punishments.go, tickets/tickets_bot.go, tickets/tickets_commands.go, tickets/tmplextensions.go, verification/verification_bot.go
Reapplying #1677 and #1684 following their revert during the 2.40.x event. They were deemed to not be the source of the issues and are now being reapplied. (I totally didn't just forget to create the pull request a month and a half ago).
=> templates: block nested template executors (reapply)

customcommands/assets/customcommands-public.html, youtube/assets/youtube.html
Custom announcements override mention everyone and mention roles. To
prevent confusion, this disables these config options when custom
announcement is enabled, and adds a popover explaining why.
Known issue:
Popovers can't seem to be enabled and disabled, despite rendering and working as intended. When I try to use `$(popovers[i]).popover('disable')` (or enable) i get `.popovers is not defined`. Current workaround is removing and re-adding all the attributes whenever the toggle is switched on or off, but this doesn't take effect until after a save. Working theory is that this could be solved with a jQuery version bump.
- Implements PR #1716 to block unsaved changes popup on public page,
which when clicked leads to a no access error. Dependant on said PR
being merged successfully.
- Fix …
=> web: simple fixes and enhancements to cc and yt

automod/effects.go, common/templates/context.go, common/templates/context_funcs.go, common/templates/context_interactions.go, notifications/plugin_bot.go, streaming/bot.go
Previously there was no support for deleting responses or followups
since `deleteMessage` was sufficient for all available use cases. Since
then Discord has added support for deletion of ephemeral messages which
may only be deleted by directly deleting the response or followup. This
PR adds that functionality.
Add a context func to delete interaction responses or followups.
Necessary for deletion of ephemeral messages.
| **Function**                                         | **Description** …
=> cc/interactions: add support for deleting responses and followups

yagpdb_docker/Dockerfile, yagpdb_docker/Dockerfile.debug, yagpdb_docker/docker-compose.debug.yml, yagpdb_docker/docker-compose.dev.yml, yagpdb_docker/docker-compose.proxied.yml, yagpdb_docker/docker-compose.proxy.yml, yagpdb_docker/docker-compose.yml
Hi, I've been self hosting the bot with podman instead of docker for a while, it doesn't automatically pull images from docker.io so I thought to fully qualify the image references. This has no effect on docker but allows podman to seamlessly build / pull the images
=> Fully qualify image references to docker.io

antiphishing/antiphishing.go
The intention here should be to initialize a slice with a capacity of  `len(bitflowAntifishResponse.Matches)`  rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW
=> fix: fix slice init length

lib/discordgo/message.go
Add the ApplicationID field to the Message struct.
If the message is an interaction- or application-owned webhook, this is
the ID of the application.
This is a suggestion from the support server:
https://canary.discord.com/channels/166207328570441728/525535451839463424/1300943054428962856
=> lib/discordgo: add application ID to message struct

automod/effects.go, automod/rulepart.go
The purpose of this is to add an AMv2 effect type that is similar to the "Send alert" option that Discord's builtin AutoMod has. It allows for mod teams to log AMv2 events (with an optional custom message) that may require additional review before an action is taken rather than relying on automatic actions alone.
The reason a custom message was included is to allow mod teams to include extra context or role pings to go along with the alert.
Here is an example of what it looks like in the UI:
Here is an example of what it looks like when a rule is triggered (custom message left blank):
=> AMv2 "Send Alert" effect/functionality

go.mod
This solves an issue with go build attempting to automatically update go to a version that doesn’t technically exist.
=> module: fix go version

common/templates/context_interactions.go
These three adjustments to common errors when using CC interactions aim to improve clarity of remedying steps users
can consider to accomplish their goals using other methods.
=> cc/interactions: improve specificity of errors

common/templates/general.go
Use reflection to compare the underlying type of arguments to convert
numbers more reliably.
Most users would expect `toInt`, `toInt64`, and `toFloat` to convert any
number, whether or not it's a defined type.
This is currently worked around by adding explicit cases for some types,
however some possible cases are missing and this approach is future-proof.
This addresses suggestion #2142 on the support server:
https://canary.discord.com/channels/166207328570441728/356486960417734666/1158622033001844746
=> customcommands: compare underlying types for number conversion

frontend/templates/index.html
Add a link to the help center to the homepage navbar header.
This is a suggestion in the support server:
https://canary.discord.com/channels/166207328570441728/356486960417734666/1289566686298636360
=> frontend: add documentation link to homepage

common/util.go
365 % 7 == 1, meaning calculating days based on remainder after dividing into weeks for a year would leave us with 1 extra day. This wouldn't be a problem if we stopped at weeks, since 365 days == 52 weeks and 1 day, however the weeks mod out to 0 so that 365 days properly becomes a year. 52 weeks ≠ 1 year. Resultantly, we need to skip every 365th day.
=> util: skip every 365th day when humanizing duration

tickets/tickets_commands.go
In the specific use case where
a) The bot does not have manage channel permissions assigned by a role
b) The bot is given manage channel permission in the ticket category
The bot is able to create tickets, but not close them. This is a simple fix which permits the bot to manage the tickets it creates. 
=> tickets: let yag manage own tickets

commands/assets/commands.html, commands/models/commands_channels_overrides.go, commands/models/commands_command_overrides.go, commands/plugin_bot.go, commands/plugin_web.go, commands/schema.go, commands/util.go, commands/yagcommmand.go
Add a command override to make responses to slash commands always ephemeral.
=> cmd: always ephemeral cmd override

common/templates/context_funcs.go
Manually insert threads into guild set after editing, closing, opening. Main objective is allowing a CC to open a thread
and immediately be able to send messages, run functions such as `addThreadMember`. Additionally keeps state more
accurate when getting info about a thread after making changes to it in a CC.
=> cc/thread: manually insert threads into guildset

common/templates/context.go
A completely visual reorganization of the context func declaration and removal of exact duplicates which is imo much 
needed, but may cause some merge conflicts downstream, hence separating into a different PR instead of lumping into 
something else.
=> templates: reorganize context func declarations

youtube/feed.go
Someone recently highlighted that the YouTube feed will throw an error, that the provided path isn't valid, if you pass it a URL for a specific section of a YouTube channel.
As the extra segments of these paths shouldn't affect the ability of the bot to fetch channels, this PR removes any effective hard requirements on segment count. It also adds an early error for empty strings as a sanity check, as a URL missing a path can't point to anything useful.
=> fix(youtube): Fix some path parsing quirks

rolecommands/menu.go
When the `-rr` flag was introduced, a condition to flip its state to `true` if the `-rr` flag was included, was introduced. For whatever reason, at some point this conditional was removed, and the flag, has not been functional when creating a Role Menu ever since
This commit introduces an inverted version of the statement used for the `-nodm`, for `-rr`, to hopefully reintroduce this functionality.
=> fix(rolecommands): Re-add `rr` check on menu setup

common/run/run.go, logs/plugin_bot.go
When generating command docs with username logging config disabled, instead of omitting the relevant commands as is the current behaviour, this PR adds a note mentioning the relevant  commands are disabled on the public instance. This 
allows for unaffected command docs to be generated including the commands in question on an instance running nickname 
logging. For instances with username logging disabled, the docs generate for the benefit of downstream forks using the 
upstream's docs while informing it's own users it won't be accessible.
=> cmddocsgen: note un/nick hist cmds disabled

common/templates/general.go
Runtime errors bypass {{catch}} and are generally unexpected.
=> Make integer divide by zero a catchable error

customcommands/assets/customcommands-database.html, customcommands/web.go, frontend/static/css/custom.css
Adds a meter of database usage and info to the database page.  Meter turns orange when 75% full and red when 90% full. There’s also a web alert at 95%. 
=> web/database: add usage indicator

customcommands/interval.go, customcommands/interval_test.go
Simplifies the cron next run time calculation to allow for simple and consistent deterministic testing.
Thank you to Joe for spending 45 minutes to point out this much easier solution to my oblivious mind.
=> cc/cron: alter time calc to aid tests

frontend/static/js/spongebob.js, frontend/templates/cp_main.html
Ask the user before leaving the page when they have unsaved changes. We
use the `onbeforeunload` event for that and return a non-empty string in
the called function.[^0]
This is also a suggestion on the support server[^1].
[^0]: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
[^1]: https://discord.com/channels/166207328570441728/356486960417734666/742956841566208093
=> frontend: ask before leaving the page with unsaved changes

customcommands/customcommands.go
Only add the "No response set" alert if no other alerts were added.
This means syntax errors in the response templates will not be
obstructed, a common issue on mobile devices.
=> customcommands web: stop redundant alerts

moderation/commands.go
As of #1761 servers can choose which commands use an ephemeral response,
on a per-override basis. This also includes moderation commands.
Moderation commands already enforced ephemeral responses though,
which some users have expressed as being undesirable.
Thus, this PR removes the hard-coded values that enforced this behaviour,
allowing servers to make their own choice about this.
=> refact(moderation): Allow non-ephemeral moderation

common/templates/context.go, tickets/assets/tickets_control_panel.html, tickets/models/ticket_configs.go, tickets/schema.go, tickets/tickets_bot.go, tickets/tickets_commands.go, tickets/tickets_web.go
Adds optional buttons which server admins can use on their server for opening and closing tickets.
- Add a new command to create a ticket menu
- By default, sends a standard message with a button allowing users to fill out a modal for their reason. Then
opens the ticket with that reason.
- With the `-message` switch, can instead append the buttons to another message sent by the bot.
- Can preset up to 9 reasons in separate buttons with switches. These buttons open with the set reason
instead of prompting the user via modal.
- If preset reasons are used, can set the `-disable-custom` switch to disable the custom reason button, only
allowing users to open with the preset reasons.
- Add new ticket config to append "Close" and/or "Close with Reason" buttons to a ticket opener message.
- Close …
=> tickets: add optional buttons to interface

stdcommands/roast/roast.go
This PR adds a footer text of `Boom, roasted!` to the embed output of the `-roast` command. 
This PR also changes the roast text to be bold, and, if a user was tagged in the command initiation, adds their username to the roast text as well.
=> Update `roast` embed

frontend/templates/cp_selectserver.html, web/discordblog/discordblog.go
Add support for the discordblog to render embeds, parse unix timestamps, and render webhooks' names. This allows bot
admins to timestamp their announcements, such as with status updates throughout a downtime event. It also allows them
to use embeds in their announcements, a not uncommon practice for bot support servers to use in their announcement
channels. Finally it allows for server admins to use webhooks, particularly relevant for tools such as Discohook.
=> discordblog: support embeds, timestampt, webhooks

reddit/assets/reddit.html, reddit/plugin_web.go
Users prefixing their input with r/ when adding Reddit feeds,
has been a persistent issue, enough to the point it had a dedicated note
on the config. page in the control panel.
This PR initially intended to address exclusively this issue,
by adding behaviour to strip leading instances of /r/
from inputs provided when adding subreddit feeds,
but also discovered the functions handling modifying
and removing these feeds, seemed to be performing redundant work
processing the subreddit names, when this work was already performed
when creating the feed.
Consequently, this PR also removes these redundant function calls,
cleaning up the handling of subreddit names in general.
=> refact(reddit): Clean up subreddit name processing

bot/util.go
With the default behavior for the discordgo.User .String() method, that don't show the # if u.Discriminator == "0"
=> Change the unknown user to remove the # on unknown user

moderation/commands.go
Report should always be ephemeral for privacy of the reporter. 
=> moderation: revert removal of report ephemeral

common/util.go
https://github.com/botlabs-gg/yagpdb/pull/1796 changed the link regex to catch URL-encoded links such as `https://%20@yagpdb.xyz`. Unfortunately, it caused a regression where text after the URL is matched. The new URL regex matches on the entirety of this text, *including the second line*:
```
https://yagpdb.xyz
and this is matched too!
```
We try to tune the regex so that it catches URL-encoded characters while avoiding the regression. The regex before #1796, after #1796, and after this PR is:
```
before #1796:    (?i)([a-z\d]+://)([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])
after #1796:     (?i)([a-z\d]+://)([\w\W_-]+(?:(?:\.[\w\W_-]+)+))([\w\W.,@?^=%&:/~+#-]*[\w\W@?^=%&/~+#-])
^^ added         ^^ added      ^^ added             ^^ added
this PR: …
```
=> util: try to fix link regex

moderation/commands.go
Users have expressed continual confusion regarding the type of ID
they should be using with the `-delwarning` command.
This commit should help rectify this to a degree.
Whilst less common, `-editwarning` uses the same naming scheme
for it's ID argument, and this will also update it accordingly
for a similar reason, even if it encounters complaints less frequently.
=> moderation: Clarify warning ID command args.

customcommands/assets/customcommands-editcmd.html, customcommands/interval.go, customcommands/interval_test.go
The hour/day blacklists were causing difficulties, these fixes address those issues and add more thorough tests for 
cron.
Currently, cron parse parses a \* in hours the same as 0,1,2...,23, and similar for dow. This poses an issue since
0,1,2...,23 != \*. Now if all hours/dows are set, the parse will leave the input unchanged rather than forcing "\*"s to
"0,1,2...23"s.
If month/dom and dow are both configured, cron will process them using OR. If user didn't want that, they wouldn't set
both in the expression. but if using day of week blacklist, in the way we do it currently that would configure it, and
then cron would use OR and mess up the user's schedule if they explicitly avoided this behaviour in their expression.
For this reason, this commit now only uses the existing method if …
=> cc/cron: fix blacklist issues

rolecommands/assets/rolecommands.html
(mb for the branch)
[Following this suggestion (✅`9` vs ❎`2` )](https://discord.com/channels/166207328570441728/356486960417734666/957040017539215361)
Just added in webTemplate
Suggestion: 
```In Role Commands, the "default" role / the role set before changing anything is set to the highest ranked manageable role. I think it would be better to either be set to "None," in which case you would not be able to save without setting one, or the lowest ranked manageable role to prevent accidents in cases where something like this (link expired) happens.```
=> (Suggestion) Removing the default higher role for rolecommand panel

autorole/bot.go, moderation/punishments.go
If a server configures autorole to give role A, and also sets up mute to remove role A, then the bot will continually attempt to add and remove role A from muted users in a loop. Fix this bug by telling autorole to ignore muted users; it already ignores timed out users.
=> autorole: ignore muted users

tickets/tickets_bot.go
Currently, using the `ticket open` command when the ticket category has 50 channels results in a Discord error of `Invalid Form Body`. This PR adds and returns a meaningful error for this case.
Before:
After:
=> tickets/tickets_bot.go: return error on reaching category channel limit

common/templates/context_funcs.go
Separated thread and channel edits for call counters. Additionally 
removed the extra harsh 2 per thread limit for functions which are not heavily rate limited as name editing is (opening, closing, locking, 
pinning threads).
=> templates: decrease thread call restrictions

logs/web.go
Add a missing quotation mark to properly display the login hyperlink
prompt when trying to view logs restricted to server members.
Reword the alert to be more accessible (include "login" in the hyperlink
text).
=> logs: fix login link in pnotify alert

common/templates/context_funcs.go
When a custom command uses more than 10 different regular expressions, the CC would error stating "too many discord api calls function." As CC regex functions do not use the Discord API, this is misleading and causes confusion around the issue.
This PR adds a new error, ErrRegexCacheLimit, which instead outputs "too many different regular expressions."
This PR also rewords and reformats the ErrTooManyAPICalls error to read "too many Discord API calls."
=> Custom Commands: New error output for regex cache limit

rolecommands/menu.go
Previously when the rolemenu create command entered an error state after attempting to send an initial message stating rolemenu setup has started, the user would receive the following output if they used the slash command; if text command, *nothing* happens.
This error is *duplicated*, using YAG's error twice, instead being followed by Discord's error.
This PR replaces the second instance of YAG's error with Discord's error.
YAG's error may be enough to get the message through that it does not have permission to send the message for the rolemenu.
However, I have left the addition of the Discord error just in case it would like to be kept, how I imagine it was meant to be.
=> Rolemenu: include Discord error in rolemenu create error output

reputation/plugin_bot.go
This PR is intended to improve the success rate for the automatic detection of thanks by adjusting the regex to match more reliably around punctuation.
The current thanks detection regex...
`(?i)( |\n|^)(thanks?\pP*|danks|ty|thx|\+rep|\+ ?\<\@[0-9]*\>)( |\n|$)`
...misses several variants of "thanks" due to how the regex will only match if punctuation followed `thanks` but not other variants like `ty` and `thx`.
The improved thanks detection regex...
`(?i)( |\n|^)?(thanks?|danks|ty|thx|\+rep|\+ ?\<\@[0-9]*\>)( |\pP|\n|$)`
...will additionally catch variants like `ty` and `thx` when there is trailing punctuation.
_Note: Matching on "danks" was not added by this PR; this variant was already in the regex when I found it. Although this has generated questions and skepticism with people whom I …
=> Improve thanks detection regex

lib/template/funcs.go
With this pr `ne` works like the `eq` function. You can give now multiple args.
**Example:**
=> [Suggestion: #2249] allow ne multiple args

automod/conditions.go, automod/triggers.go, lib/discordgo/message.go, lib/dstate/interface.go, moderation/commands.go, tickets/tickets_commands.go
Include attachments from forwarded messages across various features of
the bot which reference a message's attachments.
=> general: include attachments from forwards

reminders/plugin_bot.go
The `remindme` command's `-channel` flag was broken in https://github.com/botlabs-gg/yagpdb/commit/244f2d56fe6d53ed7e3965d3db336e31ff6c3301
This sets the target ID correctly
=> reminders: fix target channel flag

automod/assets/automod.html, automod_legacy/assets/automod_legacy.html, commands/assets/commands.html, frontend/templates/cp_nav.html, frontend/templates/index.html, reddit/assets/reddit.html, rolecommands/assets/rolecommands.html, tickets/tickets.go, twitter/assets/twitter.html, youtube/assets/youtube.html
Replace instances of `joinStr ""` with `print`, or use the separator arg
where appropriate.
=> templates: prefer print over joinStr ""

lib/discordgo/structs.go, moderation/moderation.go, moderation/plugin_bot.go, moderation/punishments.go
This PR aims to overall improve the performance of reporting external
moderation actions (i.e. actions not made through YAGPDB), by utilising
the Guild Audit Log Entry Create event fired by the Gateway whenever a
new audit log entry was created.
Due to the now more centralised nature of handling external mod actions,
we can remove some now obsolete event handlers as well, with an
additional (though probably subjective) benefit to readability of the
relevant code.
Testing reveals a rather significant speedup in posting to the mod-log
compared to the previous implementation, simply because we no longer
wait three seconds to fetch the audit log due to a potential for race
conditions. I confirmed, to the best of my ability, that the new
implementation is functionally equivalent to the old …
=> moderation: improve external mod action logging

moderation/plugin_bot.go, moderation/punishments.go
Fix e3c64084 incorrectly reporting ban authors in the modlog.
Modlog creation for unbans was moved to the audit log entry event
handler, erroneously reporting the bot user as the author of any unban,
including manual unbans with the bot's moderation command. Instead,
UnbanUser now handles modlog entry creation, and handleScheduledUnban
calls the same UnbanUser function rather than directly unbanning the
user.
=> moderation: fix unban modlog entry creation

moderation/plugin_bot.go
Ignore all non-moderation related audit log events, rather than
(re)trying to fetch nonexistant users multiple times.
Explicitly check for AuditLogChangeKeyCommunicationDisabledUntil to
differentiate between audit log member update events that change a
member's timeout and others.
AuditLogActionMemberUpdate fires for any member update event, including
things like role and nickname changes.
=> moderation: ignore non-moderation audit log events

tickets/tickets_bot.go
Defer interaction responses for ticket open and close, which can each
take longer than 3 seconds.
=> tickets: defer responses to open and close

web/web.go
This PR aims to assist baremetal hosters in port mapping to avoid 
conflicts with other baremetal instances. Adding this to the base
branch would facilitate ease of branch switching and merges.
Notably, the subset of users who are:
1. Self-hosters
2. Baremetal
3. Host multiple apps which need port 5000 and 5001 on the same 
machine
4. Frequently switch branches
5. Reverse proxy users
Is very slim. Notwithstanding, it is worth noting that:
pleasepleasepleasepleasepleasepleasepleasepleasepleaseplease
=> web: add env for ports

common/templates/context.go
Prevent limitwriter from writing leading and trailing whitespace to the template response. This ensures whitespace which
would be trimmed off of the response regardless is not written to the buffer.
Review commit by commit, the commits get increasingly more complex to approach more consistent whitespace trim.
=> templates: prevent writing leading and trailing whitespace

common/templates/context.go, common/templates/context_funcs.go, notifications/plugin_bot.go
Though there are genuine cases that may need this, they can continue to use embeds to send these invites, the key goal here is to prevent nsfw invites from showing up auto-embeded messages in a users dm.
=> strip all invites from dms in message content to prevent abuse. 

web/template.go, web/web.go
Fix typo. Doubt this function will be referenced again in the future, but if so, it can be found more easily, maybe.
=> Fix typo in tmplRoleDropdownMulti web function name

lib/discordgo/message.go, lib/dstate/helpers.go, lib/dstate/interface.go
See [`#custom-command-help`][cchelp] for a motivation of this change.
In short: Discord populates a `role_subscription_data` field on messages
of type 25 (`ROLE_SUBSCRIPTION_PURCHASE`); add it to the `Message`
object, that way we can make it available in custom commands (and
potentially elsewhere for internal usage).
[cchelp]: https://discord.com/channels/166207328570441728/871323274066407454/1356979018070491306
This is a combination of two commits:
- discordgo: add RoleSubscriptionData message field
- dstate: add RoleSubscriptionData to MessageState struct
Unfortunately I am unable to test it myself, because I don't have any
role subscriptions enabled on any of my servers--I would expect this
change to work as expected, however, as the process of adding new stuff
to the Message struct is …
=> dgo/dstate: add RoleSubscriptionData to Message struct

reddit/redditbot.go
This PR adds the up- and down-vote counts to the non-embed slow feed output. Embedded slow feed output already includes up- and down-vote counts in the footer of the embed.
=> Reddit: add up/down vote counts to non-embed slow feed

web/template.go, web/web.go
Any option where users can select channels to either ignore/require,
stage channels were missing. Add them to the predefined allowed channel
types listings (textChannelOptions, voiceChannelOptions), thus allowing
users to select these as well.
It is not entirely clear why these weren't listed, but it seems fair to
assume it was a rather simple oversight, as voice channels (once they
also got a text channel attached) evidently were added to these listings.
=> web: also list stage channels in channel list

moderation/assets/moderation.html, moderation/commands.go, moderation/config.go, moderation/models/moderation_configs.go, moderation/schema.go
Add configurable roles to the control panel which the Report command will mention upon a report being made.
=> report: optionally mention roles upon report

lib/discordgo/restapi.go, moderation/commands.go
This sets the `X-Audit-Log-Reason` header for bulk deletions via the 
`clean` command to `Deleted by $AUTHOR`.
Currently, it seems the header is neither respected nor a reason
displayed when viewing the audit log for this action, but we'll add this
functionality and wait for Discord to work their magic.
=> moderation: record moderator in audit log for bulk delete

customcommands/bot.go
After careful evaluation (pun intended), the 2k (4k for Nitro) limit
imposed on any Discord message is already enough. This command isn't
used that much anyway.
=> customcommands: remove 1k limit on evalcc

common/templates/context_funcs.go
The tmplEditMessage function does not properly transfer message flags
over to the new message object, causing some funny behaviour when, for
example, trying to set `suppress_embeds` to `true` via the
`complexMessageEdit`-builder. In other words, it does not work at all.
Copying the message flags over to the new messag fixes this.
=> templates: properly edit message flags in tmplEditMessage

automod/automod_bot.go
This fixes an issue where if a message is blocked or a multiple rules trigger on a single message, advanced automod only executes triggers for the first event.
=> Fixes to advanced automod's discord automod trigger

common/parseduration.go
The error message on line 84 has a backtick (`) instead of a single quote ('), which is inconsistent with the rest of the error message. Although this has no impact on functionality, this can cause formatting issues. If users use backticks anywhere in their response for parseArgs, the response may look messy.
=> Fix typo in the error message on line 84 (` replaced with ')

common/parseduration.go
The error that outputs on line 84 has a back tick (`) where a single quote (') should be. This causes some strange visual effects in Discord when another back tick appears in the response.
=> Corrected line 84 (changed back tick to single quote)

lib/dice/dice.go, lib/dice/dice_test.go, lib/dice/eote_test.go, lib/dice/std.go, lib/dice/std_test.go, lib/dice/versus_test.go
Fixes an issue with `/roll rpg-dice` where it was possible to make YAGPDB to never answer and eventually timeout due to a bug in this library that has since been solved there. For more info, see `dice_test.go:55`
Since the used version of the library is based on a fork, I also made sure to keep all custom changes to the code.
To replicate the issue, try to input the following command to YAGPDB:
```
/roll rpg-dice:1d1k2
```
=> Update library `dice` to the latest version

automod/effects.go
Clarify the tooltip of the delete multiple messages effect, that it only
applies to the infracting user's messages.
=> automod: clarify Delete Multiple Messages effect tooltip

logs/plugin_bot.go
In the case where a user has no roles, the resulting Roles field value remains as an empty string which causes an error. This sets the value to `None` if there are no roles present.
=> logs/whois: avoid empty roles field value

README.md
- Added clear explanations for both built-in and reverse proxy HTTPS configurations.
- Explained what `--https=false` and `--extHttps=true` do in simple terms. (For more long terms the user should investigate more)
Checked [Documentation](https://github.com/botlabs-gg/yagpdb-docs-v2) and I didnt find anything releated to this (Self-hosting setup)
=> README: clarify and simplify HTTPS setup instructions in README

tickets/tickets_commands.go
Fixes a typo in the argument description for tickets menucreate
=> typo fix: `cutsom` to `custom`

common/templates/general.go
As title says.
While we're here, some food for thought; does it also make sense to do
the same for the other bitwise operations, excluding NOT?
If so, I can just add those to this PR as well.
=> templates: allow more than two args for bitwiseAnd

common/templates/general.go
Since #1937, `bitwiseAnd` (erroneously) always returns 0. The issue is that the named result `res int` is zero-initialized at the start of the function, and `0 & n == 0` for any `n`.
Fix the function by initializing `res` to the first argument instead.
There is an additional behavior change here in that calling `bitwiseAnd` with zero arguments is now forbidden. However, it makes no sense to call `bitwiseAnd` with no arguments anyway and the original implementation prior to #1937 required exactly two args, so I don't imagine this will break any users in practice.
=> templates: fix bitwiseAnd

bot/bot.go, lib/discordgo/gateway.go, lib/discordgo/structs.go, lib/jdshardmanager/dshardmanager.go
Currently, the bot only connects one shard every 5 seconds, which can take approximately 3 hours in cases of complete outages. The max_concurrency provided by discord allows to safely start the bot much much quicker.
=> use max_concurrency provided by discord gatway/bot endpoint to identify shard. 
